### PR TITLE
feat: add provider metrics

### LINKED ISSUE #648: Metrics: add provider API calls metric
We want to know how many API calls are being made towards a specific secret provider API. 
For a first iteration i would propose to add a simple `counter` metric with
(1) `provider` label that defines which provider is being requested: `aws/secretsmanager`, `aws/parameterstore`, `gcp/secretsmanager`, `vault/kv`, `azure/keyvault`, etc..

(2) `result` label that defines if the call has been successful or not: `SUCCESS` or `ERROR`
```
provider_calls{provider="aws/secretsmanager", result="SUCCESS"} 42
```

To get deeper insights it may be valuable to have a label for the ExternalSecret namespace and/or name. This information however is not passed into the provider.

### PR DESCRIPTION
**Pull request by moolen**
## Proposed Changes

This adds a counter metric `provider_api_calls_count` that observes the results of upstream secret provider api calls.

All `external-secrets` providers are covered, plus some community providers:
* AWS SecretsManager
* AWS ParameterStore
* Hashicorp Vault
* GCP SecretManager
* Azure KeyVault
* IBM Cloud Secrets Manager
* Kubernetes
* GitLab
* Webhook

(1) Observability
It allows an user to break down issues by provider and api call by observing the status=error|success label. More details around the error can be found in  the logs.

(2) Cost Management
Some providers charge by API calls issued. By providing observability for the number of calls issued helps users to understand the impact of deploying ESO and fine-tuning `spec.refreshInterval`.

(3) Rate Limiting
Some providers implement rate-limiting for their services. Having metrics
for success/failure count helps to understand how many requests are issued by a given ESO deployment per cluster.

I also took the time to prep a Grafana Dashboard and provide some guidance on SLIs for the operator:

eso-dashboard-1
eso-dashboard-2

## Related Issue

Fixes #648

## Proof of Work

See dashboard screenshots above. I installed the operator via helm as well as `kube-prometheus-stack` to test that ServiceMonitor picks up the `cert-controller` and `webhook` metrics.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by moolen** [comment]
@knelasevero do you have some time to look at this :pray: ?

**Comment by knelasevero** [comment]
Will have a look on Friday!

**Comment by knelasevero** [comment]
This is great! I was able to test gcp on friday, and wanted to test a few more, but don't want to block this one getting in :D

lgtm!

**Comment by onedr0p** [comment]
@moolen I tried importing your dashboard included in this PR but get

```
Failed to upgrade legacy queries Datasource prometheus was not found
```

I think this dashboard might need to be updated to pull the default Prometheus datasource instead of hard coding it.

**Comment by moolen** [comment]
Thanks for reporting this, fixed it in #2148. Had to properly export the dashboard.

**Comment by onedr0p** [comment]
Hm. Interesting, it still doesn't appear to work.

```
Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS} was not found
```

FWIW I'm trying to import it via the Grafana helm chart this way:

https://github.com/onedr0p/home-ops/blob/1aa308cfe3ca5aa1cb0e3cc641ca4c2deea21ae9/kubernetes/apps/monitoring/grafana/app/helmrelease.yaml#L175L177

**Pull request merged**
