### PR TITLE
Remove unnecessary space before a colon

### PR DESCRIPTION
**Pull request by dubs11kt**
Remove unnecessary spaces in helm chart.

### CODE REVIEW

**Comment by moolen** [comment]
hey @dubs11kt could you please sign your commit? 🙏

**Comment by dubs11kt** [comment]
@moolen 
Thank you for your response!
I signed my commit. Cloud you check, please?

**Comment by moolen** [comment]
There are currently 3 commits in this PR, 2 of them aren't signed (1 merge commit, 1 change). Can you please rebase and squash your commits so theres only a single, signed commit? :pray:

**Comment by dubs11kt** [comment]
@moolen 
I'm sorry.
I rebased and squashed my commits into one.

**Comment by moolen** [comment]
Hey @dubs11kt no worries! It's now squashed but the signoff is missing :)

**Comment by dubs11kt** [comment]
@moolen 
Thank you kindly!!!
I'm not familiar with OSS activities.

I signoff with `git commit --signoff`. Cloud you check, please?

**Review by moolen — APPROVED** [review]
LGTM :)
Thank you for your contribution!

**Pull request merged**
