### PR TITLE
Vault ldap and jwt/oidc auth methods

### PR DESCRIPTION
**Pull request by xxxbobrxxx**
Adding Vault backend auth methods:
- [ldap](https://www.vaultproject.io/docs/auth/ldap)
- [jwt/oidc](https://www.vaultproject.io/docs/auth/jwt)

implements issue #150

### CODE REVIEW

**Review by mcavoyk — APPROVED** [review]
LGTM

**Comment by knelasevero** [comment]
LGTM as well :)

**Pull request merged**
