### PR TITLE
bug fix: merge secret metadata instead of overriding

### PR DESCRIPTION
**Pull request by Shanti-G**
## Problem Statement

The secret metadata is being overridden instead of being merged. This is breaking our secret automation.

## Related Issue

Fixes https://github.com/external-secrets/external-secrets/issues/2864

## Proposed Changes
Reverting the changes made in https://github.com/external-secrets/external-secrets/pull/2705, as per the discussion [here](https://github.com/external-secrets/external-secrets/issues/2864#issuecomment-1804828252)

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by Shanti-G** [comment]
Hi @moolen , hope these changes look good. I have tested this locally and the secret metadata is being merged as expected.

**Comment by moolen** [comment]
Unfortunately, looking at #2862, i think we can't simply revert that commit. Maybe its worth looking into server-side apply.

**Comment by shuheiktgw** [comment]
I'll take it over from here 🙇 
https://github.com/external-secrets/external-secrets/issues/2864#issuecomment-1806594681

**Comment by moolen** [comment]
sorry, meant #2682 :bow:

**Comment by shuheiktgw** [comment]
I'm closing this PR since it's been resolved by https://github.com/external-secrets/external-secrets/pull/2900

**Pull request closed without merging**
