### PR TITLE
Add support for Google Cloud Identity

### PR DESCRIPTION
**Pull request by mouhsen-ibrahim**
If the name of the service account secret is kept
empty, this means we want to use Google Cloud Identity
to authenticate against the GCP project

### CODE REVIEW

**Comment by knelasevero** [comment]
I did not know that the client just falls down to workload identity by default, which makes it very clean at the end.

I am thinking here and maybe it would make sense to just make auth key optional for gcp then? Like:
image

And then when we want to use GCP-WI we just create a store passing just the projectID.
image

What do you think?

Please run `make check-diff` and `make fmt` whenever you open a PR :)

**Comment by mouhsen-ibrahim** [comment]
@knelasevero you are right, if we make the auth key optional this is cleaner, I will modify the code today and update the PR

**Comment by knelasevero** [comment]
@moolen do we want to have a field to explicitly choose that the user wants to use GCP-WI, or omitting credentials fields is enough?

**Comment by knelasevero** [comment]
Just checked again and we just omit it for was with pod identity. I guess we can just omit here. :+1:

**Comment by knelasevero** [comment]
Gonna merge this one cause I have some people in need of this feature :smile: Please re-open the issue if you feel that something is missing. (I will take care of e2e tests for this)

**Comment by renaudguerin** [comment]
Fantastic stuff @mouhsen-ibrahim @knelasevero !
When can we expect a new release that includes this ?

**Comment by knelasevero** [comment]
@renaudguerin it's out already! v0.3.4 here or on artifacthub.

https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets

**Pull request merged**
