### PR TITLE
Add support for Docker UBI images

### PR DESCRIPTION
**Pull request by mrgadgil**
As originally discussed with @moolen in https://github.com/external-secrets/external-secrets/issues/1192
 Collaborating with @IdanAdar
Addressing review comments mentioned in the comment https://github.com/external-secrets/external-secrets/issues/1518#issuecomment-1237331226

### CODE REVIEW

**Comment by mrgadgil** [comment]
@moolen Can you please review the PR and share your thoughts. Thank you.

**Review by moolen — CHANGES_REQUESTED** [review]
Hey, thanks for taking a shot at this! Can we DRY this one out? I feel that there's too much copy-paste here, that makes it hard to maintain.

Now, taking a look at it again i'd see if GitHub Actions matrix strategy would do the job to build multiple images :thinking:

**Comment by IdanAdar** [comment]
Thanks @moolen let’s see what you come up with.

**Comment by moolen** [comment]
I've had something like this in mind: #1574

**Comment by IdanAdar** [comment]
I believe given @moolen’s other PR we can now close this one.

**Comment by IdanAdar** [comment]
Superseded by https://github.com/external-secrets/external-secrets/pull/1574

**Pull request closed without merging**
