### PR TITLE
Add support for Yandex Lockbox

### PR DESCRIPTION
**Pull request by AndreyZamyslov**
Issue: [#308](https://github.com/external-secrets/external-secrets/issues/308)

This is the implementation itself. We have tested it manually and it looks like it is pretty workable.
I am also going to add some tests and documentation soon.

However just to ensure I am heading in the right direction could you please take a brief look at the code?

### CODE REVIEW

**Comment by knelasevero** [comment]
Hey @AndreyZamyslov! Thanks for the PR!

I also want to do some manual tests with lockbox to accompany my review here. I created an account there and I am waiting for Lockbox to be available on my free trial. A quick look over code tells me that you are going in the right direction.

image

When I have access to it I will give a bit more feedback here :)

**Comment by AndreyZamyslov** [comment]
@knelasever We used the instructions below for testing.
Hope this helps :)

**Prerequisites**
1) Yandex.Cloud CLI installed: https://cloud.yandex.com/en-ru/docs/cli/quickstart
1) Create k8s namespace `ns1`:
  `kubectl create namespace ns1`
1) Create lockbox secret `es1`:
  yc lockbox secret create --name es1 --payload '[{"key": "password","textValue": "p@$$w0rd#1"}]'
1) Run the External Secret Operator (for example, via `make run`)


**Steps**
1) Create service account `sa1` giving the access to lockbox secret `es1`:
```
yc iam service-account create --name sa1
yc lockbox secret add-access-binding --name es1 --service-account-name sa1 --role lockbox.payloadViewer
yc lockbox secret list-access-bindings --name es1 # just to ensure the correct access binding has been added
yc iam key create --service-account-name sa1 --output key1.json # write the created authorized key to key1.json file
```

2) Create k8s secret `yc` and put the authorized key there:
```
kubectl --namespace ns1 create secret generic yc --from-file=authorized-key=key1.json
```

3) Create SecretStore object:
```
kubectl --namespace ns1 apply -f - <<< '
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: ss
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: yc
          key: authorized-key
'
```

4) Create ExternalSecret object:
```
kubectl --namespace ns1 apply -f - <<< '
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: es1
spec:
  secretStoreRef:
    name: ss
    kind: SecretStore
  target:
    name: secret1
  data:
  - secretKey: password
    remoteRef:
      key: e6qlehp8d8j4c84tct65 # ID of lockbox secret es1
      property: password # (optional) payload entry key of lockbox secret es1
'
```

**Result**
k8s secret secret1 is accessible:
```
kubectl --namespace ns1 get secret secret1 -ojson | jq -r ."data"."password" | base64 -D
```

**Comment by knelasevero** [comment]
Awesome! It helped a lot. Since Lockbox always expects lockbox secrets to store key values (you cant just throw text directly), implementation and tests can go in the same direction as we have for Hashicorp vault (and you already went that way, which is perfect). I tested dataFrom behaviour, data without property and with property and everything seems fine. Templating seems fine as well. 

Looking at the code, I am also pleased with what I see. :)

I am good with merging this when we have some tests :smile:

**Comment by AndreyZamyslov** [comment]
Added tests.
Documentation is on the way.

**Comment by AndreyZamyslov** [comment]
@knelasevero  I've added the docs.

But also I suddenly realized there is a problem with making requests to Lockbox in lockboxProvider :)
A new connection (via ycsdk.SDK instance) is created and closed for each secret refresh now instead of reusing one long-lived connection.

I want to add some more commits fixing this.

**Comment by knelasevero** [comment]
Thanks for adding docs!

> But also I suddenly realized there is a problem with making requests to Lockbox in lockboxProvider :)
> A new connection (via ycsdk.SDK instance) is created and closed for each secret refresh now instead of reusing one long-lived connection.

Do you mean that we close the connection and create a new client every time in the controller? That's intended, right?

Or do you mean something else?

**Comment by AndreyZamyslov** [comment]
@knelasevero I have added the changes I wanted and a bit more tests.
Could you please take another look at this? Are these changes good enough to be merged?


> Do you mean that we close the connection and create a new client every time in the controller? That's intended, right?

Yes, I think that's ok in general.
But it was not a very good idea to create a new Yandex.Cloud SDK object for every NewClient() call in lockboxProvider. It was my bad and I've fixed it in the latest commit

**Comment by AndreyZamyslov** [comment]
I see that `check-diff` failed. But `make check-diff` passes if I run it locally.

**Comment by knelasevero** [comment]
Rebase with master and make generate. We got some changes on types and CRDs :)

**Comment by knelasevero** [comment]
Thanks @AndreyZamyslov ! Gonna merge soon!

**Comment by AndreyZamyslov** [comment]
> Thanks @AndreyZamyslov ! Gonna merge soon!
That's awesome!

**Comment by AndreyZamyslov** [comment]
@knelasevero Thank you for your help! It was really pleasant contribution experience :)

Just one more question, how soon will the new version be released?

**Comment by knelasevero** [comment]
@AndreyZamyslov thanks for the feedback! Also thanks so much for the PR again :) 

I have some important fixes to get out there, and they should get out asap, lockbox will go together with them. I would expect another release this week, latest next week

**Comment by AndreyZamyslov** [comment]
@knelasevero Great, thanks!

**Pull request merged**
