### PR TITLE
Implemented `updatePolicy: IfNotExists` for AWS Secret Store

### LINKED ISSUE #3380: Implement Pushsecrets `updatePolicy: IfNotExists` for AWS Secrets Manager
**Describe the bug**
Just tried to push a secret and did not work. v0.9.15-2

**To Reproduce**
```
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: postgresql
  namespace: controlplane
spec:
  updatePolicy: IfNotExists
  deletionPolicy: Delete
  refreshInterval: 168h
  secretStoreRefs:
    - name: default
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgresql
  data:
    - match:
        remoteRef:
          remoteKey: controlplane/postgresql-smg
```

**Expected behavior**
The secret to be pushed

**Screenshots**
``
{"level":"error","ts":1713276193.4958684,"msg":"Reconciler error","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","PushSecret":{"name":"postgresql","namespace":"controlplane"},"namespace":"controlplane","name":"postgresql","reconcileID":"8012f29d-4fe7-4c13-a811-d08d54b51574","error":"could  not verify if secret exists in store: not implemented","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).proc  essNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}   
{"level":"info","ts":1713276208.7876587,"logger":"provider.aws","msg":"using aws session","region":"eu-west-1","external id":"","credentials":null}
``

### PR DESCRIPTION
**Pull request by ppatel1604**
## Problem Statement

What is the problem you're trying to solve?
Currently, `pdatePolicy: IfNotExists` with aws secret store does not work. The push secret checks if secret exist for the secret manager which is set to `not implemented` so push controller can't proceed with creating the secret

## Related Issue

Fixes #3380

## Proposed Changes

How do you like to solve the issue and why?
Implemented a check on the `SecretExist` which will return either true or false with err depending on the reponse received from the aws client. If the secret exist check return ResourceNotFound Err then it will return true and push_controller will be able to continue with its process

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [ ] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
hi @ppatel1604 ! Can you add some unit tests on the newly implemented `SecretExists` method? 😄

**Comment by ppatel1604** [comment]
> hi @ppatel1604 ! Can you add some unit tests on the newly implemented `SecretExists` method? 😄

@gusfcarvalho Implemented some unit test for newly  implemented `SecretExists` method 🙂

**Comment by gusfcarvalho** [comment]
@ppatel1604 there were just some problems with linting. You can check them with `make lint`. I believe `make fmt` should already fix them for you.

**Comment by ppatel1604** [comment]
Thanks @gusfcarvalho . I did the `make fmt` which fixed it.

**Review by gusfcarvalho — APPROVED** [review]

**Comment by gusfcarvalho** [comment]
@ppatel1604 Thanks for your contribution!!

**Pull request merged**
