### PR TITLE
feat: update Pulumi provider for GA

### PR DESCRIPTION
**Pull request by dirien**
## Problem Statement

Pulumi ESC is now GA. This PA makes the ESO provider ready for the GA of Pulumi ES

## Related Issue

Fixes #...

## Proposed Changes

How do you like to solve the issue and why?

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by Skarlso** [comment]
@dirien Hello 👋  Can you take care of the failed lint and test please so we can get the update into the new 0.10.4 version please? :) Thanks.

**Comment by dirien** [comment]
@Skarlso done! Thanks for the heads-up

**Comment by dirien** [comment]
@Skarlso missed one test.

**Comment by Skarlso** [comment]
https://github.com/external-secrets/external-secrets/issues/3921

**Comment by Skarlso** [comment]
@dirien looks like you are missing a go mod tidy. :)

**Comment by dirien** [comment]
Aaaaarrggghh.... Thanks for the your patience with me @Skarlso! 

It should be now good!

**Comment by Skarlso** [comment]
This is a Minor update, right? It's a breaking change because of the project requirement?

Do you think it could be made optional or would that just not work?

**Comment by Skarlso** [comment]
Well, Pulumi is in alpha anyways, so it's expected to break. :)

**Review by Skarlso — APPROVED** [review]

**Comment by Skarlso** [comment]
Nevertheless, we clearly need to flag this in the Release notes.

**Comment by dirien** [comment]
@Skarlso: Yes. The thing is, with the introduction of Projects inside Pulumi ESC, all exsisting secretes are automaticaly moved to the `default` project.

> Users will be able to create new environments in the default project until Nov 30, 2024. Starting Dec 1, 2024, users will not be able to create new environments in the default project.

https://www.pulumi.com/blog/esc-projects-environment-tags-launch/

So, i did not want to set the default value of project to default only to then create a new PR and folks using ESO with Pulumi needs to come back and fix them.

You can link in the release notes to the blog post for more details or point to the Pulumi ESC docs in general.

**Pull request merged**
