### PR TITLE
Add Support for fips regions.

### PR DESCRIPTION
**Pull request by tomelliot16**
## Problem Statement

What is the problem you're trying to solve?

## Related Issue

Fixes #...

## Proposed Changes

How do you like to solve the issue and why?

## Checklist

- [ ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ ] All commits are signed with `git commit --signoff`
- [ ] My changes have reasonable test coverage
- [ ] All tests pass with `make test`
- [ ] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by moolen** [comment]
Hey, could you please signoff your commits? :pray:
Otherwise LGTM

**Comment by tomelliot16** [comment]
I'm just running tests on my side to make sure this 100% works. Will sign commit as soon as I verify

**Comment by tomelliot16** [comment]
Confirmed it worked 🎉 Secret was synced.
```
{"level":"info","ts":1698268587.6035829,"logger":"provider.aws","msg":"using aws session","region":"us-east-1-fips","external id":"","credentials":null}
```
Going to go fix lint and sign commit

**Comment by tomelliot16** [comment]
@moolen I think this is ready now

**Review by moolen — APPROVED** [review]
LGTM, thank you for this enhancement :rocket:

**Pull request merged**
