### PR TITLE
Stability docs update

### PR DESCRIPTION
**Pull request by IdanAdar**
- IBM Cloud Secrets Manager posture is `stable`
- Added 0.6.0

### CODE REVIEW

**Review by moolen — APPROVED** [review]
LGTM :+1:

**Comment by IdanAdar** [comment]
@moolen When does the website get regenerated to include the changes?

**Comment by gusfcarvalho** [comment]
hey @IdanAdar ! It should be available here already https://external-secrets.io/main/ . It will become "latest" whenever we do a new release

**Comment by moolen** [comment]
It is there on `main`: https://external-secrets.io/main/stability-support/

But not for the latest 0.6.0 release because this was merged after the release.

I guess we'd like to have it for the 0.6 release, but unfortunately we don't have a way to backport these changes

**Comment by moolen** [comment]
Lol.. as i was typing :D

**Pull request merged**
