### PR TITLE
Revert "3012 - Probes for external-secrets"

### PR DESCRIPTION
**Pull request by Skarlso**
Reverts external-secrets/external-secrets#3131

https://github.com/external-secrets/external-secrets/issues/3212

### CODE REVIEW

**Comment by Skarlso** [comment]
Not sure why Helm is failing since it's a revert.

**Review by IdanAdar — APPROVED** [review]

**Comment by fdberlking** [comment]
> Not sure why Helm is failing since it's a revert.

You should not revert the whole commit, otherwise you don't fix the issues with onboardbase and fortanix snapshots. At least that's my interpretation here:

```yaml
 FAIL  test crds	deploy/charts/external-secrets/tests/crds_test.yaml
	- should match snapshot of default values

		- asserts[0] `matchSnapshot` fail
			Template:	external-secrets/templates/crds/secretstore.yaml
			DocumentIndex:	0
			Path:	
			Expected to match snapshot 1:
				--- Expected
				+++ Actual
				@@ -2417,2 +2417,30 @@
				                       type: object
				+                    fortanix:
				+                      description: Fortanix configures this store to sync secrets using the Fortanix provider
				+                      properties:
				+                        apiKey:
				+                          description: APIKey is the API token to access SDKMS Applications.
				+                          properties:
				+                            secretRef:
				+                              description: SecretRef is a reference to a secret containing the SDKMS API Key.
				+                              properties:
				+                                key:
				+                                  description: |-
				+                                    The key of the entry in the Secret resource's `data` field to be used. Some instances of this field may be
				+                                    defaulted, in others it may be required.
				+                                  type: string
				+                                name:
				+                                  description: The name of the Secret resource being referred to.
				+                                  type: string
				+                                namespace:
```

**Comment by fdberlking** [comment]
Damn it, I was a bit too late 😄 You just merged

**Comment by Skarlso** [comment]
Argh :D

**Comment by Skarlso** [comment]
It's okay, I guess we'll fix that in a separate commit.

**Comment by fdberlking** [comment]
> It's okay, I guess we'll fix that in a separate commit.

I'll quickly do it, I gained some experience during this week 😄

**Comment by Skarlso** [comment]
Thanks! :D :D Much appreciated. :D

**Comment by fdberlking** [comment]
> Thanks! :D :D Much appreciated. :D

Here we go: https://github.com/external-secrets/external-secrets/pull/3215

**Pull request merged**
