### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by IdanAdar**
Signed-off-by: Idan Adar <iadar@il.ibm.com>

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
LGTM

**Comment by gusfcarvalho** [comment]
We should also discuss if its worth to bring IBM Cloud to the internally maintained providers! WDYT @IdanAdar @moolen @knelasevero ? Should we discuss this in our next meeting?

**Comment by moolen** [comment]
Yeah, sounds good!

**Comment by gusfcarvalho** [comment]
Added as an agenda topic for the next meeting! 😄

**Pull request merged**
