### PR TITLE
Fix: Update Label for Documentation

### PR DESCRIPTION
**Pull request by KAZYPinkSaurus**
## Problem Statement

[The examples](https://external-secrets.io/main/api/generator/webhook/) show labels that are deprecated in the latest version.

## Related PR

- #3753

## Proposed Changes

I replaced the key with the latest one.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by KAZYPinkSaurus** [comment]
1 errored checks .🤔

**Comment by Skarlso** [comment]
@KAZYPinkSaurus You can ignore the licence check it has been failing for a while now.

**Comment by gusfcarvalho** [comment]
I was just remembering we probably need to update the webhook guide as well... IIRC there is another secret ref that needs to be updated to include labels

**Comment by KAZYPinkSaurus** [comment]
@gusfcarvalho 
Thank you for your important comment.
Would it be possible to address the issue you pointed out separately from this PR?
If not, could you give me more specific instructions so that we can fix it together?

Thank you in advance.

**Comment by gusfcarvalho** [comment]
it is adding the same labels to here :) https://github.com/external-secrets/external-secrets/blob/main/docs/provider/webhook.md

Sure, I can do it, but since this is the scope of this PR, IMO it makes sense to really fix is everywhere it needs to fix 😄

**Comment by KAZYPinkSaurus** [comment]
thank you for marge!

**Pull request merged**
