### PR TITLE
fix(docs): webhook docs weren't linked properly

### PR DESCRIPTION
**Pull request by moolen**
webook docs were missing in the sidebar

### CODE REVIEW

**Comment by knelasevero** [comment]
Still missing from README?

**Comment by knelasevero** [comment]
Do we want to add this one as community maintained by the contributor?

**Comment by knelasevero** [comment]
Looks all good!

**Comment by knelasevero** [comment]
Seems like it failed to render https://external-secrets.io/provider-webhook/

🤔

**Comment by moolen** [comment]
build failed, fixed it

**Pull request merged**
