### PR TITLE
Add a Note for Vault Namespaces

### PR DESCRIPTION
**Pull request by benjamin-issa**
Adds a brief note on the `namespace` attribute in the `SecretStore` object.

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
hi @benjamin-issa ! Thank you for your contribution!

**Comment by gusfcarvalho** [comment]
Paul seems to be asleep already 😅 I'll merge this one manually.

**Comment by benjamin-issa** [comment]
Thanks! :)

**Pull request merged**
