### PR TITLE
Update contact email (#2948)

### LINKED ISSUE #2948: Update contact email
The contact email given in Security.md, Readme.md and coc.md  (contact@external-secrets.io) seem to be outdated.
This needs to be fixed and replaced with the new email cncf-ExternalSecretsOp-maintainers@lists.cncf.io

### PR DESCRIPTION
**Pull request by rrgodhorus**
## Problem Statement

The contact email is outdated.

## Related Issue

Fixes #2948 

## Proposed Changes

Update it to new email cncf-ExternalSecretsOp-maintainers@lists.cncf.io

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by rrgodhorus** [comment]
Hello @knelasevero. Mind reviewing this ?

**Comment by knelasevero** [comment]
Sorry for the delay @rrgodhorus, I am on sick leave. Anyways LGTM :) thanks

**Review by knelasevero — APPROVED** [review]

**Pull request merged**
