### PR TITLE
Create ADOPTERS.md

### PR DESCRIPTION
**Pull request by knelasevero**
Create ADOPTERS.md similar to https://github.com/linkerd/linkerd2/blob/main/ADOPTERS.md and get some initial names here

### CODE REVIEW

**Comment by alekc** [comment]
@knelasevero mm let me double check with the management :)

**Comment by alekc** [comment]
no from me, at least for now. Sorry about that.

**Comment by knelasevero** [comment]
@ahmedmus219 can you check?

**Comment by ahmedmus219** [comment]
> @ahmedmus219 can you check?

Hi , I need to return to the my company's management , once approved I will update the adopters file.

Cheers,
Ahmed

**Comment by andyleap** [comment]
Please add Mixpanel (https://mixpanel.com) to the list of adopters!

**Comment by knelasevero** [comment]
I am guessing others are having trouble getting this approved. I am going to merge for now, we can add more later

**Pull request merged**
