### PR TITLE
IBM Provider: enable ESO to pull secrets by name

### PR DESCRIPTION
**Pull request by Shanti-G**
## Problem Statement

ESO for IBM Provider requires secret ID to pull secret from Secrets Manager

## Related Issue

https://github.com/external-secrets/external-secrets/issues/2210

## Proposed Changes

This PR enables ESO to pull IBM Provider secrets by name. For this, the list of secrets matching the name provided by user to a secret ID is fetched and then the relevant details of the secret are retrieved.
The documentation has also been updated accordingly.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by Shanti-G** [comment]
Hi @idan, this PR is to address https://github.com/external-secrets/external-secrets/issues/2210 as discussed earlier.

**Review by nitnis — APPROVED** [review]

**Review by IdanAdar — APPROVED** [review]

**Comment by IdanAdar** [comment]
@moolen PR is approver. Can you help with merging it?

**Comment by Shanti-G** [comment]
Thanks @nitnis @IdanAdar @moolen for the help.
I have documentation updated in this PR and would like to know if there are additional steps to be taken for it to be reflected in the site https://external-secrets.io/v0.8.1/provider/ibm-secrets-manager/.
As per my understanding, docs are per release number. If so, when is the next release being planned. Thanks again.

**Comment by moolen** [comment]
Next release comes right after #2325; earöy next week i guess

**Pull request merged**
