### PR TITLE
gramar2 - intuitive not intuative

### PR DESCRIPTION
**Pull request by aviadkray**
## Problem Statement

intuitive not intuative

## Related Issue

Fixes #...

## Proposed Changes

How do you like to solve the issue and why?

## Checklist

- [x ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x ] All commits are signed with `git commit --signoff`
- [ x] My changes have reasonable test coverage
- [ x] All tests pass with `make test`
- [ x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by Skarlso** [comment]
Can you please do these in a single pull request instead of opening a new one for all grammar issues? :) 

Thank you! 🙇 🙏

**Review by shuheiktgw — APPROVED** [review]

**Comment by shuheiktgw** [comment]
Oops, sorry I missed the comment!

**Comment by Skarlso** [comment]
@shuheiktgw yah there is already one here https://github.com/external-secrets/external-secrets/pull/2991

**Review by moolen — APPROVED** [review]
LGTM, thanks for the fix :books:

**Pull request merged**
