### PR TITLE
chore: refactor provider

### PR DESCRIPTION
**Pull request by moolen**
This PR refactors a couple of providers to make them more readable and reusable for the upcoming generator PR.

The general approach is that a provider implementation should be structured following the `type Provider interface` and `type SecretsClient interface`.

### CODE REVIEW

**Comment by knelasevero** [comment]
So in short it means we stop embedding stuff to make the provider struct be both things, and have them separate, right? (just commenting here so it's clear to anyone coming to contribute new providers and we can reference)

**Comment by knelasevero** [comment]
Looks great!

**Comment by moolen** [comment]
> So in short it means we stop embedding stuff to make the provider struct be both things, and have them separate, right? (just commenting here so it's clear to anyone coming to contribute new providers and we can reference)

yes, well put!

**Pull request merged**
