### PR TITLE
feat: add helm release

### LINKED ISSUE #67: Fix helm chart  install
The helm chart install as documented here is failing with this error 
Installing the chart as documented [here](https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets)   fails with the below error

 `% helm repo add external-secrets https://external-secrets.github.io/external-secrets 

Error: looks like "https://external-secrets.github.io/external-secrets" is not a valid chart repository or cannot be reached: failed to fetch https://external-secrets.github.io/external-secrets/index.yaml : 404 Not Found`

Tried installing the chart directly from the chart source and ran into the below with default values

Failed to pull image "ghcr.io/external-secrets/external-secrets:0.1.0": rpc error: code = Unknown desc = Error reading manifest 0.1.0 in ghcr.io/external-secrets/external-secrets: name unknown

### PR DESCRIPTION
**Pull request by moolen**
Goal: semi-automatically release helm charts and eso container image

A `RELEASE.md` is in this PR that outlines the release process.

Examples:
* [GitHub Release w/ commit msg](https://github.com/moolen/external-secrets/releases/tag/v0.1.1)
* alternative: [GitHub Release Changelog using PRs](https://github.com/moolen/external-secrets/releases/tag/untagged-89603f5decec37616c10) (that would force us to label ALL PRs properly)

### Changelog gen
Changelog is generated from git commit titles.

The previous docs pipeline used to override the helm `index.yaml`, that's why we need a custom deployment script there.
The charts will be available via `https://charts.external-secrets.io`. I've set up an 302 that points to `external-secrets.io`. Not sure if we _really_ need it.

fixes #67 #105

### CODE REVIEW

**Comment by knelasevero** [comment]
The alternative link does not open for me: [GitHub Release Changelog using PRs](https://github.com/moolen/external-secrets/releases/tag/untagged-89603f5decec37616c10)

To be honest, this is way better than what I thought about doing :stuck_out_tongue_closed_eyes:.

So there is no way to use both actions without one of them overriding the other? I mean helm/chart-releaser-action and peaceiris/actions-gh-pages. I think it also makes sense to open an issue on one/both of them and let them know. I imagine this use-case being very common.

Anyways LGTM!

**Comment by moolen** [comment]
i fixed the link, i had to publish the release (it was a draft which is private by default). 

> So there is no way to use both actions without one of them overriding the other?

~Yes. i checked that,~ i didn't check the docs of that module :sweat:. seems like `keep_files` does the trick!

**Pull request merged**
