### PR TITLE
fix: increase default QPS/Burst to 50/100

### PR DESCRIPTION
**Pull request by thesuperzapper**
## Related Issue

related https://github.com/external-secrets/external-secrets/issues/4180
related https://github.com/external-secrets/external-secrets/issues/2837
related https://github.com/external-secrets/external-secrets/issues/3258

## What's the problem?

External-Secrets v0.11 significantly improved our performance and reduced the number of API calls we make (https://github.com/external-secrets/external-secrets/pull/4086), but the default QPS / Burst limits (shared by every client accessing the Kubernetes API) are still too low for even moderate scale users (100+ ExternalSecrets that refresh 60s).

The current default values are `5 QPS` and `10 Burst`, as these are the defaults for [`rest.Config`](https://pkg.go.dev/k8s.io/client-go/rest#Config).

For reference, other large projects use __much__ higher values:

- [Istio uses `100/500`](https://github.com/istio/istio/blob/d0f01576ca3010dd565aaa084d0e1c9ded39da07/pilot/pkg/features/tuning.go#L118-L130)
- [Kyverno uses `300/300`](https://kyverno.io/docs/installation/customization/#container-flags)
- [Crossplane uses `20/30`](https://github.com/crossplane/crossplane/blob/fe31b2d1e7f2cc7ff718ef23e7f20db825398ae7/cmd/crank/beta/trace/trace.go#L129-L139)

Our defaults are way too low, and can cause us to never be able to clear through the work queue if there are enough ExternalSecrets, especially when we now make more decisions based on caching, and can thus blow through our work queue much faster.

## What does this PR do?

Very simply, it changes the default values to:

- `--client-qps` = `50`
- `--client-burst` = `100`

## Are there any concerns?

The new defaults of 50/100 are still very reasonable and are unlikely to be a problem on any functional real-world cluster, even if we sustained 50 QPS for an extended period.

The only problem I see is that users who have been experiencing performance issues until this point might have set `--concurrent` to a large number. As this effectively nothing right now (because all threads share the same QPS limit), users might accidentally DDoS their cluster now that we have a higher default. However, 50/100 is still pretty low, so I dont think its a problem.

## Checklist

- [X] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [X] All commits are signed with `git commit --signoff`
- [X] My changes have reasonable test coverage
- [X] All tests pass with `make test`
- [X] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@Skarlso @gusfcarvalho I am interested to hear your thoughts on this change.

I think the proposed new defaults are reasonable and will reduce the amount of people who fail to adopt ExternalSecrets because it does not sync fast enough.

**Comment by gusfcarvalho** [comment]
> I don't mind that change but would also consider to entirely disable it when APF is enabled (there's a utils package somewhere for detection, can't find it atm)

I am by far no APF expert (or even user for what its worth) - but isnt it going to block/rate whatever configuration we have regardless what we set code wise? don't we want to be as fast as possible on these cases?

**Comment by moolen** [comment]
I mean: set qps & burst to -1, which will result in no client side throttling. Instead we solely rely on server side rate limiting. 

So yes, with that we're as fast as possible/allowed

**Comment by thesuperzapper** [comment]
Since this setting is just applying to the internal rest.Config, it's possible that -1 already works (if that is implemented upstream).

But certainly that's not a safe config for the default, and this PR is only about changing the default.

**Review by moolen — APPROVED** [review]
LGTM

**Pull request merged**
