### PR TITLE
Kick ClusterExternalSecret reconciliation when a Namespace is updated

### PR DESCRIPTION
**Pull request by shuheiktgw**
## Problem Statement

I've updated the ClusterExternalSecret controller to start the reconciliation when a namespace is updated to improve usability.  Thank you for your review 🙂 

## Related Issue

Fixes https://github.com/external-secrets/external-secrets/issues/2351

## Proposed Changes

Watch Namespaces and kick reconciliations if necessary.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Review by moolen — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by shuheiktgw** [comment]
Thank you!

**Comment by 12345ieee** [comment]
So now that this has been merged could I deploy my CES with a refreshTime of 0 (or 1 billion years, I need to check if 0 works) but still have the generated ES be available instantly in new namespaces?

**Comment by shuheiktgw** [comment]
@12345ieee Yes, IIUC, that is correct 🙂  I've created another issue to discuss if we could remove the refresh interval field or not, so please follow it if you are interested in the topic. https://github.com/external-secrets/external-secrets/issues/2502

**Pull request merged**
