### PR TITLE
Add standalone Dockerfile

### PR DESCRIPTION
**Pull request by snarlysodboxer**
As mentioned in https://github.com/external-secrets/external-secrets/issues/1327, it would be nice to be able to build the Docker image without external dependencies. This adds a `Dockerfile.standalone` and a little documentation to support that.

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
Hi @snarlysodboxer ! I've just seen the commit was created under "Docs" user. I think this is due to make docs command generating credentials in order for it to push code.

Do you mind setting up your username again and force-pushing this commit? from what I've seen its all good.

**Comment by snarlysodboxer** [comment]
> Do you mind setting up your username again and force-pushing this commit? from what I've seen its all good.

@gusfcarvalho Oh man, that's a bit embarrassing. I was wondering why my commits weren't verified. - Good to go now.

**Pull request merged**
