### PR TITLE
chore: add eso tools page

### PR DESCRIPTION
**Pull request by Sn0rt**
## new section of eso page

Add a new page to share tools that can help manage certain scenarios with the external-secret operator.

## Related Issue

https://github.com/external-secrets/external-secrets/discussions/3854

## Proposed Changes

add new page

## Checklist

- [ ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ ] All commits are signed with `git commit --signoff`
- [ ] My changes have reasonable test coverage
- [ ] All tests pass with `make test`
- [ ] I ensured my PR is ready for review with `make reviewable`

@gusfcarvalho

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
Hey! Thank you for the contribution 🥳 

Although I think this is already implemented 😄  - i added a comment in the issue https://github.com/external-secrets/external-secrets/issues/3869#issuecomment-2330856033

**Comment by Sn0rt** [comment]
> Hey! Thank you for the contribution 🥳
> 
> Although I think this is already implemented 😄 - i added a comment in the issue [#3869 (comment)](https://github.com/external-secrets/external-secrets/issues/3869#issuecomment-2330856033)

aha. But I think my conversion tool is still very useful, and it would be even better if it could appear in the external secert ecosystem.

**Comment by gusfcarvalho** [comment]
I agree :smile:  maybe changing this PR to add it to our docs session under `community` ?

**Comment by Sn0rt** [comment]
> I agree 😄 maybe changing this PR to add it to our docs session under `community` ?

Sounds good!

**Comment by Sn0rt** [comment]
@gusfcarvalho hi. can you help me to solve "License Compliance — 6 issues found" ? I not understand what's this.

**Review by gusfcarvalho — APPROVED** [review]

**Comment by gusfcarvalho** [comment]
> @gusfcarvalho hi. can you help me to solve "License Compliance — 6 issues found" ? I not understand what's this.

inconvenience on our side - nothing to worry

**Pull request merged**
