### PR TITLE
[FEATURE] Customizable encoding of logging timestamp

### PR DESCRIPTION
**Pull request by RiccardoColella**
Objective of this commit is to allow logs to be more readable.

Default log ts encoding in the logger employed (zap) is unix time. This leads to logs not much human-readable. This change introduces the possibility to customize the ts with a set of preconfigured encodings: one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'

Default value does not change

### CODE REVIEW

**Comment by RiccardoColella1A** [comment]
Hello @moolen @gusfcarvalho! I know there is code duplication in the PR. How do you advise to solve it?

**Comment by RiccardoColella** [comment]
Hello @moolen @gusfcarvalho! I know there is code duplication in the PR. How to you advise to solve it?

**Comment by moolen** [comment]
Hey @RiccardoColella this is fine, this can be ignored :sweat_smile:

**Review by moolen — APPROVED** [review]
thanks for this addition, LGTM :heart:

**Pull request merged**
