### PR TITLE
How to manage secrets in OpenShift using Vault and External Secrets Operator blog reference

### PR DESCRIPTION
**Pull request by pandeybk**
How to manage secrets in OpenShift using Vault and External Secrets Operator blog reference

### CODE REVIEW

**Comment by knelasevero** [comment]
I think we can also add the YouTube video specifically here: https://github.com/external-secrets/external-secrets/blob/main/docs/eso-demos.md

**Comment by moolen** [comment]
saw the video posted on reddit aswell, thanks a lot ;)

**Comment by knelasevero** [comment]
Let me merge this and add the other stuff :)

**Comment by knelasevero** [comment]
It's there :). You might need to Ctrl Shift R

https://external-secrets.io/main/eso-demos/

**Pull request merged**
