### PR TITLE
add missing install of cosign in the CIs pipelines

### PR DESCRIPTION
**Pull request by cpanato**
follow up of #845 which was missing to install cosign 

My apologies for breaking the pipeline.

cc @moolen @knelasevero

### CODE REVIEW

**Comment by knelasevero** [comment]
Thanks!

**Comment by cpanato** [comment]
:)

```
$ COSIGN_EXPERIMENTAL=1 cosign verify ghcr.io/external-secrets/external-secrets:main


Verification for ghcr.io/external-secrets/external-secrets:main --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - Any certificates were verified against the Fulcio roots.

[{"critical":{"identity":{"docker-reference":"ghcr.io/external-secrets/external-secrets"},"image":{"docker-manifest-digest":"sha256:d4b56693254b7237c584314b1372ecd307cafbe59808f35fdc95545773dd7768"},"type":"cosign container image signature"},"optional":{"Bundle":{"SignedEntryTimestamp":"MEUCIQCVCBrM25NPxLutmwK3bPlWpqp/WjkKEhS+GodqTNw52QIgTnGtoxPktQ571PhjKRc6o+oUzTIEjacjjalr0nDFt34=","Payload":{"body":"eyJhcGlWZXJzaW9uIjoiMC4wLjEiLCJraW5kIjoiaGFzaGVkcmVrb3JkIiwic3BlYyI6eyJkYXRhIjp7Imhhc2giOnsiYWxnb3JpdGhtIjoic2hhMjU2IiwidmFsdWUiOiIxZTRmM2E3YTk0ZTBhZWFlNWIyNGZkMjBhYmIxMTRmZmI3ZDA2ZGEzODE3NjYwYjJkOTAyYjk2ZWRkOTE1NjJkIn19LCJzaWduYXR1cmUiOnsiY29udGVudCI6Ik1FUUNJQldHVjc2bE1ncGxHZFY4b1FPYndPRmNpdFlxanQ0SnRncmhDVVlnNDMwVUFpQXhzbWYzV0RhSU1sc29yQzhPU2M2T0hITHFYZldxUzcwa0FheWllWmRyTlE9PSIsInB1YmxpY0tleSI6eyJjb250ZW50IjoiTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkhla05EUVhGRFowRjNTVUpCWjBsVVRsUk1jM1o0UnpWNlkxRXhjVEZoWmpKR1JWVjNjelZFUTNwQlMwSm5aM0ZvYTJwUFVGRlJSRUY2UVhFS1RWSlZkMFYzV1VSV1VWRkxSWGQ0ZW1GWFpIcGtSemw1V2xNMWExcFlXWGhGVkVGUVFtZE9Wa0pCVFZSRFNFNXdXak5PTUdJelNteE5RalJZUkZSSmVRcE5SRTE1VFVSSmVrMXFSVEJQUm05WVJGUkplVTFFVFhsTlJFbDZUWHBGTUU0eGIzZEJSRUphVFVKTlIwSjVjVWRUVFRRNVFXZEZSME5EY1VkVFRUUTVDa0YzUlVoQk1FbEJRa2gzY3pFelowdHdaWHA0TTFOU1UxZG9lalJzVFc5c015OHhSM1pPVGpONGREbFJZMGgxTlU1ME4yVlVhbGxzYnpacGIwdE9PRTBLVHk5WFUxaDRPVXRITWpGVE5qY3ZNekpZV1UxWGVtOXVabmRUUlRaelEycG5aMGhPVFVsSlFubFVRVTlDWjA1V1NGRTRRa0ZtT0VWQ1FVMURRalJCZHdwRmQxbEVWbEl3YkVKQmQzZERaMWxKUzNkWlFrSlJWVWhCZDAxM1JFRlpSRlpTTUZSQlVVZ3ZRa0ZKZDBGRVFXUkNaMDVXU0ZFMFJVWm5VVlUyWTNWa0NtVTFWVll3WWxVck9HdFNjMEY2UTNOd1EyZzJkRzgwZDBoM1dVUldVakJxUWtKbmQwWnZRVlZYVFVGbFdEVkdSbkJYWVhCbGMzbFJiMXBOYVRCRGNrWUtlR1p2ZDJGM1dVUldVakJTUVZGSUwwSkhSWGRZTkZwa1lVaFNNR05JVFRaTWVUbHVZVmhTYjJSWFNYVlpNamwwVERKV05HUkhWbmxpYlVaelRGaE9iQXBaTTBwc1pFaE5kbHBZYURCYVdFcDFXVmQzZEdNeVZtcGpiVll3WTNrNGRWb3liREJoU0ZacFRETmtkbU50ZEcxaVJ6a3pZM2s1YW1GVE5UVmlWM2hCQ21OdFZtMWplVGx2V2xkR2EyTjVPWFJaVjJ4MVRVUnJSME5wYzBkQlVWRkNaemM0ZDBGUlJVVkxNbWd3WkVoQ2VrOXBPSFprUnpseVdsYzBkVmxYVGpBS1lWYzVkV041Tlc1aFdGSnZaRmRLTVdNeVZubFpNamwxWkVkV2RXUkROV3BpTWpCM1NGRlpTMHQzV1VKQ1FVZEVkbnBCUWtKblVWQmpiVlp0WTNrNWJ3cGFWMFpyWTNrNWRGbFhiSFZOUWtGSFEybHpSMEZSVVVKbk56aDNRVkZSUlVGclRrcE5RemhIUTJselIwRlJVVUpuTnpoM1FWRlZSVWxYVmpSa1IxWjVDbUp0Um5OTVdFNXNXVE5LYkdSSVRYWmFXR2d3V2xoS2RWbFhkM1JqTWxacVkyMVdNR042UVZOQ1oyOXlRbWRGUlVGWlR5OU5RVVZEUWtGU2QyUllUbThLVFVSWlIwTnBjMGRCVVZGQ1p6YzRkMEZSVFVWTFIxRjZXVlJCZWsxSFdURmFWRUV6V1dwb2JGcEVhekJQVkVreFdtMVNiVTFVVVRGTmVrMHhXbGRWZHdwTk1rcHBXa2RPYkU1cVJYZERaMWxKUzI5YVNYcHFNRVZCZDAxRVlWRkJkMXBuU1hoQlRWZEpaMmxCUjFGalJtZGxaazlYZUZsdE1EQjJaalV5YTBWd0NqVlBXbFJHY1d4dVUzSnZPVFpFYUdOa1l6Wm1iSGhUZHpWWmFuUlZkamswYkM5bWQxUlJTWGhCVUVkVldFTk9OVzlZU0d0eFNrbE9NMHN3WVZndmMwd0tXV0ZFVVZoSlQyZDFOWHBYZEcxc1JsVnVNM2R3TjBnemRUWk5SbW92TmtkbVpsQnFTbTFaVjFkM1BUMEtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0ifX19fQ==","integratedTime":1647818509,"logIndex":1741757,"logID":"c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d"}},"Issuer":"https://token.actions.githubusercontent.com","Subject":"https://github.com/external-secrets/external-secrets/.github/workflows/ci.yml@refs/heads/main"}}]
```

**Pull request merged**
