### PR TITLE
Add FluxCD GitOps documentation

### PR DESCRIPTION
**Pull request by achetronic**
I just added documentation about the GitOps deployment of the entire External Secrets stack (from CRDs to CRs) using FluxCD. This example is fully functional

### CODE REVIEW

**Comment by achetronic** [comment]
@knelasevero @moolen 

Hello again,
Now I have documented all the process. I hope you like this approach :)

Need a review here,
Thank you!

**Comment by moolen** [comment]
awesome @achetronic, thank you so much for taking the time to document it in-depth!

**Comment by achetronic** [comment]
> awesome @achetronic, thank you so much for taking the time to document it in-depth!

Thank you for the cool project. I will keep contributing as much as I can :)

**Pull request merged**
