### PR TITLE
Propose a blog post about ESO and IBM Secrets Manager

### PR DESCRIPTION
**Pull request by xsa**
Add a link to a blog article I wrote about ESO and IBM Secrets Manager.

### CODE REVIEW

**Comment by xsa** [comment]
> There seems to be no description in your Pull Request.Please add an understanding of what this change proposes to do and why it is needed

Please re-open. Description is in there.

**Comment by gusfcarvalho** [comment]
Hey @xsa ! Thank you for your content! We really appreciate it!

**Comment by gusfcarvalho** [comment]
it seems Paul is not liking this PR, so I'm merging it automatically! Sorry for that. Thanks again for the contribution!

**Comment by xsa** [comment]
> it seems Paul is not liking this PR, so I'm merging it automatically! Sorry for that. Thanks again for the contribution!

Thanks @gusfcarvalho -- Tell Paul i don't take it personally 🤖😂

**Pull request merged**
