### PR TITLE
Conjur E2E Tests for K8s JWT Authentication

### PR DESCRIPTION
**Pull request by szh**
## Problem Statement

1. The Conjur provider for ESO supports both API Key and JWT authentication, but only the API Key authentication is included in the E2E test suite (added in #3120).
2. Conjur users are limited in the way they can integrate with ESO using Conjur's JWT authentication options. Specifically, Conjur allows either a JWT that includes the workload (pod, application) identity in one of the claims (currently supported), as well as by including the identity in the URL used to authenticate with the JWT. This latter option is not yet supported in ESO.

## Related Issue

This is a follow up from #3120, which added the E2E tests for API Key authentication with Conjur.

## Proposed Changes

1. Add E2E tests to ESO that run against a Conjur OSS instance that's configured to allow JWT authentication using a Kubernetes service account JWT.
2. Add a "HostID" configuration option to the Conjur provider's JWT config object which, when provided, will be included in the authentication URL to allow authentication to Conjur with a JWT that doesn't include the workload ID in a claim.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by shuheiktgw** [comment]
@szh It seems one of the jobs fails. Could you take a look at it and fix it? 🙏

**Comment by szh** [comment]
@shuheiktgw I rebased and I think that should fix it. Please let me know

**Comment by Skarlso** [comment]
@szh Can you please attend the two new Sonar issues? :) Thank you! After that, I think this is good to go. :)

**Comment by szh** [comment]
No idea what I just did there to this PR, I'm going to close and reopen.

**Pull request closed without merging**
