### PR TITLE
feat: edit all required changes for recursive option

### LINKED ISSUE #3938: [Infisical] - I'm not able to read recursive secrets
**Describe the bug**
With Infisical store, when the password is on the root path, it works well. When the password is inside a folder, it is not found (the find + regex show it well)

**Additional context**
I open a pull request to improve this behaviour

### PR DESCRIPTION
**Pull request by Tchoupinax**
Greetings!

## Problem Statement

After few time spent to read a password from a folder, I saw that there is no way to configure the recursive option with Infisical and this option is required when you want to read secrets from folders. I did the necessary changes. 

## Related Issue

Fixes #3938 

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by Skarlso** [comment]
@Tchoupinax Hello. :) Please sign the commit so I can merge it. :) Here are the instructions on how to https://github.com/external-secrets/external-secrets/pull/3939/checks?check_run_id=30494278458

Thanks!

**Comment by Tchoupinax** [comment]
Hello @Skarlso !
Thank for your message. I added the required signatures and I did minor changes about API. It works well (activate and remove the recursive option)

**Comment by Tchoupinax** [comment]
However, I don't know what is happening with this test
```
FAIL
coverage: 60.8% of statements
FAIL    github.com/external-secrets/external-secrets/pkg/utils  1.751s
```

**Comment by Skarlso** [comment]
@Tchoupinax It doesn't appear to be failing on CI?

**Comment by Skarlso** [comment]
@Tchoupinax Hello hello. Any progress?

**Comment by Tchoupinax** [comment]
If it's OK in the CI I trust more it than my local environment :)

**Comment by Skarlso** [comment]
Let's see how it goes. :)

**Comment by Skarlso** [comment]
@Tchoupinax You need to run `make check-diff` again and commit what changed.

**Comment by Tchoupinax** [comment]
Done!

**Comment by Skarlso** [comment]
@Tchoupinax Can you sign all your commits please? :)

**Comment by Tchoupinax** [comment]
Hello @Skarlso,

We will make it! :p
I rebased, signed commits and I rechecked the make diff command. We are ok!

**Review by Skarlso — APPROVED** [review]

**Comment by Tchoupinax** [comment]
Thanks @Skarlso for your support!

**Comment by salv0** [comment]
Hey @Tchoupinax and @Skarlso thank you both for this! I've been struggling with the same issue for a couple days before landing here 😅 

Question: when can this be released (with the Helm chart)? 
Thank you!

**Comment by Skarlso** [comment]
Err, eventually I get there to do another release. :D I don't have it on my todo list yet. :)

**Comment by salv0** [comment]
@Skarlso ok thank you for the prompt response..is there a workaround/anything I can do in the meantime to retrieve and use secrets in a specific folder?

**Comment by Skarlso** [comment]
I don't know of any, sorry. :/

**Pull request merged**
