### PR TITLE
temporarily removing ossf checks for helm release

### PR DESCRIPTION
**Pull request by gusfcarvalho**
## Problem Statement

What is the problem you're trying to solve?

## Related Issue

Fixes #...

## Proposed Changes

How do you like to solve the issue and why?

## Checklist

- [ ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ ] All commits are signed with `git commit --signoff`
- [ ] My changes have reasonable test coverage
- [ ] All tests pass with `make test`
- [ ] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Review by Skarlso — APPROVED** [review]

**Comment by keatontaylor** [comment]
Can we get more of an explanation on why this was turned of in favor of fixing the issue?

**Comment by jemc** [comment]
@gusfcarvalho @Skarlso The PR template for this repository prompts you to enter a "Problem Statement" for a reason - because without that context, people like @keatontaylor and @hanscg and I are left wondering *why a security feature was disabled for a release* for a software component that handles sensitive data for a large number of organizations.

I'm not accusing anyone here of malicious intent... I expect that there's a perfectly innocuous reason for this temporary workaround - It's just that *I want to actually see the explanation* instead of guessing about it.

In the future please be sure to give an explanation for the changes you make, as the PR template requires. And please don't merge PRs which lack such an explanation. It's a simple norm that takes only a minute or two to comply with, and it makes things much better for everyone involves.

**Comment by Skarlso** [comment]
Oh  I approved it hahaha.

**Comment by Skarlso** [comment]
@jemc Fair point. We were in the process of releasing that was breaking and we wanted to get on. :)

Honestly, it's not too much to look at the action and see the reasons: https://github.com/external-secrets/external-secrets/actions/runs/7687294794/job/21064717685#step:6:7

```
Run echo "" | gpg --dearmor --output keyring.gpg
gpg: no valid OpenPGP data found.
Error: Process completed with exit code 2.
```

This is still a problem. :) No idea how to solve it since data is missing and we don't really have that kind of access.

**Comment by jemc** [comment]
I did see the "no valid OpenPGP data found" message, but that doesn't really explain it, and I'm still confused about what's going on even after reading your message.

- what do you mean by "we don't really have that kind of access"?
    - who is "we"?
    - access to what specifically?

- what was the initial intention behind this gpg feature in the pipeline?
    - who set it up, and why?
    - what are the implications of having disabled it?
    - when it was originally set up, did it have the necessary data?
        - if so, what changed?

**Comment by keatontaylor** [comment]
@moolen sorry to ping you here, but I think the above comment needs to be addressed. Can we please get some eyes on this?

**Pull request merged**
