### PR TITLE
Update docs for ExternalSecrets's refreshInterval

### LINKED ISSUE #4079: Clarify type of `refreshInterval`
It is unclear to me what type the `ExternalSecret.spec.refreshInterval` field has:

https://github.com/external-secrets/external-secrets/blob/51fabd49a54f311e35df4de0a50d48ba2f8449ff/apis/externalsecrets/v1beta1/externalsecret_types.go#L345-L349

I would like to write `2.5h`, but I don't know if that is legal. I can trial-and-error my way to the answer, but I would prefer if the API spec was clearer with exactly what type `refreshInterval` is. 🙂

### PR DESCRIPTION
**Pull request by lindhe**
## Problem Statement

Before this change, it was a bit unclear what type of `ExternalSecret.spec.refreshInterval` was.

## Related Issue

Fixes #4079

## Proposed Changes

This change aims to clarify the documentation for `ExternalSecrets.spec.refreshInterval` by adding examples and referring to Go's `Duration` type.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by lindhe** [comment]
After running `make reviewable` there were a bunch of `items.type=null` objects added to the JSON schema:

Screenshot 2024-11-11 185957

These changes seem to exist on main too, so I didn't add them to my commit. I only added the changes that relates to my original change.

**Comment by lindhe** [comment]
The CI errors seem to be unrelated to my changes.

There's a failure because of the diff I mentioned:

image

And then there seems to be a `TOOMANYREQUESTS` error when downloading Trivy db: 
image

**Comment by moolen** [comment]
> After running `make reviewable` there were a bunch of `items.type=null` objects added to the JSON schema:
> 
> Screenshot 2024-11-11 185957
> 
> These changes seem to exist on main too, so I didn't add them to my commit. I only added the changes that relates to my original change.

That has been fixed with the latest release v1.6.3. Your PR ran with v1.6.2. Re-running CI :crossed_fingers:

**Review by moolen — APPROVED** [review]
LGTM, thank you for the improvement :bow:

**Pull request merged**
