### PR TITLE
release: update helm chart to v0.10.0

### PR DESCRIPTION
**Pull request by Skarlso**
## Problem Statement

What is the problem you're trying to solve?

## Related Issue

Fixes #...

## Proposed Changes

How do you like to solve the issue and why?

## Checklist

- [ ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ ] All commits are signed with `git commit --signoff`
- [ ] My changes have reasonable test coverage
- [ ] All tests pass with `make test`
- [ ] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Review by IdanAdar — DISMISSED** [review]

**Comment by Skarlso** [comment]
@IdanAdar Ah thanks! I forgot to update the version in the helm test file. :D 🙇

**Review by IdanAdar — APPROVED** [review]

**Comment by Skarlso** [comment]
AWS tests passed, it failed to deleted the infrastructure:
```
2024-08-03T07:37:47.5575313Z [31m│[0m [0m[1m[31mError: [0m[0m[1merror deleting EC2 VPC (vpc-0f997bdeff09da8b9): DependencyViolation: The vpc 'vpc-0f997bdeff09da8b9' has dependencies and cannot be deleted.
2024-08-03T07:37:47.5579580Z [31m│[0m [0m	status code: 400, request id: ee2f6d81-e0c3-46d2-bc38-20b9fc46f0c7[0m
```

**Pull request merged**
