### PR TITLE
chore: upgrade beyondtrust go client library

### PR DESCRIPTION
**Pull request by btfhernandez**
## Problem Statement

Upgrade beyondtrust go client library.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by Skarlso** [comment]
Hello @btfhernandez.

Any potential breaking changes we should be aware of?

**Comment by btfhernandez** [comment]
> Any potential breaking changes we should be aware of?

Hello @Skarlso, we made some improvements in our library, fixed a minor issues, but general behavior keep the same.

**Comment by Skarlso** [comment]
@btfhernandez please run make check-diff locally then commit the changes.

**Comment by btfhernandez** [comment]
> @btfhernandez please run make check-diff locally then commit the changes.

Hello @Skarlso, I'm having next issue running command:

```
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/felipe/integratios/btfhernandez/kubernetes/external-secrets/hack/api-docs/../../.
See 'docker run --help'.
make[1]: *** [Makefile:50: build] Error 125
make[1]: Leaving directory '/home/felipe/integratios/btfhernandez/kubernetes/external-secrets/hack/api-docs'
make: *** [Makefile:210: docs] Error 2
```

Do you have any idea about the reason ?

**Comment by Skarlso** [comment]
I don't know. :/ Optionally, just run `go mod tidy`.

**Comment by btfhernandez** [comment]
> I don't know. :/ Optionally, just run `go mod tidy`.

@Skarlso Done, Thank you!

**Review by Skarlso — APPROVED** [review]

**Pull request merged**
