### PR TITLE
feat: generate client code

### PR DESCRIPTION
**Pull request by amine7536**
## Problem Statement

Our project needs a Go client to work with `ExternalSecrets` CRDs, but currently, there is no available clientset. To solve this, we have been using a private repository to generate the clientset, but it would be much easier if the clientset was provided by this project directly.

## Proposed Changes

This PR generates the client code for all CRDs using `gen-client`.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by Skarlso** [comment]
Hi.

Sorry, but we don't have the capacity to maintain all of this generated code through breaking changes and API updates.

Especially since we are considering a major overhaul of how we are dealing with providers.

I know it's generated, but generation breaks too and has to be adopted and this is just to much to worry about.

I'm but one maintainer for this project, but the seeing as the others are busy right now, it's already a challenge to keep up with basic things.

**Comment by gusfcarvalho** [comment]
👍  to what Gergely said.

We have been accepting contribution from different people on different things - like OLM, Rancher, etc - and then not have the support from them after the initial contribution.

I would only be willing to consider this PR above if we have proper commitment from you/your team @amine7536 to support it whenever it breaks (and I mean - if it breaks, and you can't support it, we will revert and remove it 😄).

**Comment by amine7536** [comment]
Hi, I understand the concern about long-term maintenance. I can support this feature if any issues arise.

**Comment by Skarlso** [comment]
@amine7536 Okay, please add documentation with the warning that if you ever would disappear this feature will no longer be supported and that you state that with in control of full body and mind. :D And I'm not joking. :)))) ( okay half joking with the body and mind thing :D )

**Comment by gusfcarvalho** [comment]
@moolen  @knelasevero  I guess this one will also need your input as other maintainers 😅

**Comment by moolen** [comment]
Nothing to add from my side. I think it is a great addition to have and i share the concerns in regards to maintainability.

**Comment by gusfcarvalho** [comment]
@amine7536 can you add a note to https://external-secrets.io/latest/introduction/stability-support/ saying that all clientset apis are delivered with limited community support, and that they may be removed without any further notice to the user?

**Comment by thesuperzapper** [comment]
I think projects are generally moving away from explicit client generation, and are instead encouraging people to use the [`client.Client`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client) from [`controller-runtime`](https://github.com/kubernetes-sigs/controller-runtime) (even outside of Kubebuilder apps).

See this issue for a discussion about why it's recommended to simply use `controller-runtime` and import the generated interface types (for the CRDs) from this project: https://github.com/kubernetes-sigs/kubebuilder/issues/1152

When using `controller-runtime`, you also get the benefit of being able to use [`cache.Cache`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache) if you want to avoid making requests to the Kubernetes API, at the expense of caching them in memory using a ListWatch.

---

So, my vote is not to introduce a clientset, as its just another thing to maintain.

**Comment by Skarlso** [comment]
I agree with @thesuperzapper

**Comment by amine7536** [comment]
Thank you all for your input and considerations. After reviewing the discussion, particularly @thesuperzapper 's [comment](https://github.com/external-secrets/external-secrets/pull/4030#issuecomment-2466555294). If the trend in the Kubernetes ecosystem is to use controller-runtime, I think we should abandon this Pull Request.

**Pull request closed without merging**
