### PR TITLE
Fix typo privatKey in multiple files

### PR DESCRIPTION
**Pull request by IdanAdar**
Fixes https://github.com/external-secrets/external-secrets/issues/3556

### CODE REVIEW

**Comment by Skarlso** [comment]
This is a breaking change. Just flagging that. :)

**Comment by IdanAdar** [comment]
@moolen Do we want to address it then? Too bad that a typo fix causes a breaking change.

**Comment by Skarlso** [comment]
It might still be okay depending on usage and how old that thing is. Also, we can release it with a minor version. That's what versioning is for after all, I think.

**Comment by moolen** [comment]
When was the typo released? Not too long ago, right?
I'd make the change and add a big red warning in the release notes.
We never intended to release a typo

**Comment by IdanAdar** [comment]
Okay, so now need to understand why the typo fix is failing in CI / lint and CI /check-diff...

**Review by Skarlso — APPROVED** [review]

**Comment by lindhe** [comment]
Sorry for being late for the discussion. Thanks for pointing out that this is a breaking change, that is important to consider! I just want to point out that external-secrets is still on major version 0, which, [according to semver](https://semver.org/#spec-item-4), may introduce breaking changes on any new version. Just saying. :angel:

**Pull request merged**
