### PR TITLE
Add tweaks for secretsManager tests

### PR DESCRIPTION
**Pull request by gabibeyer**
For readability and scalability, create a struct with default
test case values, then use anonymous function "tweaks" with only the
changes from default to test on.

### CODE REVIEW

**Comment by gabibeyer** [comment]
#44

**Comment by knelasevero** [comment]
Thanks @gabibeyer! This is really clean! Now looking at it we could have done the next test down bellow together with this one, right? (my bad btw, I should have noticed this :sweat_smile:) Since they are probably going to re-use some of the tweaks, like setAPIErr. We can make the tweaks that are used for more than one test global, if it makes sense. What do you think?

**Review by moolen — APPROVED** [review]
awesome, thank you 👍 !

**Comment by gabibeyer** [comment]
Thank you for the review @moolen

**Pull request merged**
