### PR TITLE
Fix documentation for namespace in ClusterSecretStore

### PR DESCRIPTION
**Pull request by nasirhm**
I was facing SecretsSyncedError due to namespace being not set in case of a ClusterSecretStore.

Where should i add the NOTE ?

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
hi @nasirhm ! Although this is already explained elsewhere in the docs, I think it's fair to be told on the provider section, but I think we can be more verbose and tell it everywhere, and not only on the GCP provider. Can you include the same comments for the other providers as well?

**Comment by nasirhm** [comment]
sure, i'll update it accordingy.

**Comment by gusfcarvalho** [comment]
Hi @nasirhm ! Did you have the time to go over the other providers? If you want, we can take it from here.

**Comment by albertollamaso** [comment]
Hi, I ran into same issue using aws provider.

aws keys are created in kube-system namespace.

Below config was returning error: `unable to create session: invalid ClusterSecretStore: missing AWS AccessKeyID Namespace`

```
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: test-store
  namespace: kube-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key

```

Once changed to:

```
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: test-store
  namespace: kube-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
            namespace: kube-system
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
            namespace: kube-system

```

It worked and started synced the secrets: `Message:                Secret was synced`

**Comment by gusfcarvalho** [comment]
Hi @albertollamaso ! Please note that this is the actual behavior as per spec and documentation. This PR is more to make it clearer in provider section as a reminder.

I did ran a quick glimpse on AWS provider examples, but I didn't find a mention to a ClusterSecretStore. Is your snippet from an example in the docs?

**Comment by albertollamaso** [comment]
hi @gusfcarvalho 

AWS provider section does not mention ClusterSecretStore. We should consider adding it but not related to this PR as you mentioned before.

**Comment by nasirhm** [comment]
> Hi @nasirhm ! Did you have the time to go over the other providers? If you want, we can take it from here.

I totally lost track of it, I'll add it here.

**Comment by gusfcarvalho** [comment]
Hey @nasirhm ! If you're having time issues on your side, we can catch on where you left, and add the rest of the notes on the other providers. Please, let me know!

**Comment by gusfcarvalho** [comment]
Hi @nasirhm ! We will merge your PR and add the remaining contributions to other providers! Thank you for pointing it out!

**Pull request merged**
