### PR TITLE
Remove failing license scan

### PR DESCRIPTION
**Pull request by austinpray-mixpanel**
Removes 
>image

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
Sorry, what’s the reason for this contribution? 😅 we are a project under CNCF umbrella

**Comment by austinpray-mixpanel** [comment]
> Sorry, what’s the reason for this contribution? 😅 we are a project under CNCF umbrella

It seemed broken so I removed the badge 🤷

**Comment by knelasevero** [comment]
Thanks for your concern.

We should remove packages violating the check, or adde them to an ignored list, or fix the check. We should not remove the badge

**Comment by austinpray-mixpanel** [comment]
Now when I click the badge I see an failing license scan. Before I was seeing a 404 page.

image

Seems like it's all working now!

**Pull request closed without merging**
