### PR TITLE
feat: add SYNCED to ClusterExternalSecretStatusCondition

### PR DESCRIPTION
**Pull request by Hayden-Chang**
## Problem Statement

What is the problem you're trying to solve?

Add SYNCED to ClusterExternalSecretStatusCondition to show the amount of synced secret.

## Related Issue

Resolves https://github.com/external-secrets/external-secrets/issues/2419

## Proposed Changes

Before change:
image

After change:
image

When the secret in both two namespaces are synced:
image

How do you like to solve the issue and why?

When clusterexternalsecret_controller reconciles, it checks whether the secret is synced in each namespace.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by shuheiktgw** [comment]
Hi, thank you for putting together the PR, @Hayden-Chang! Let me describe what I think

1. As I commented [here](https://github.com/external-secrets/external-secrets/issues/2419#issuecomment-1608824667), ClusterExternalSecretController's responsibility is not making sure each child ExternalSecret is ready or not. It is ExternalSecretController's concern. So storing ExternalSecret statuses in ClusterExternalSecret's status does not seem to align with the design decision to me.
2. The name `SYNCED` does not seem right to me because what it means is not only the ExternalSecret is synced but also the ExternalSecret is ready.

**Comment by Hayden-Chang** [comment]
> Hi, thank you for putting together the PR, @Hayden-Chang! Let me describe what I think below
> 
> 1. As I commented [here](https://github.com/external-secrets/external-secrets/issues/2419#issuecomment-1608824667), ClusterExternalSecretController's responsibility is not making sure each child ExternalSecret is ready or not. It is ExternalSecretController's concern. So I'm not too sure if storing ExternalSecret statuses in ClusterExternalSecret's status aligns with the design decision.
> 2. The name `SYNCED` does not seem right to me because what it means is not only the ExternalSecret is synced but also the ExternalSecret is ready.

Hi, @shuheiktgw , Thanks for your reply.

1. As we know, ClusterExternalSecret could create multiple ExternalSecrets, so I think it's reasonale to have an UX of ClusterExternalSecret to check the final status of all its related ExternalSecrets. At least it's friendly to our users.

2. A `synced` ExternalSecret must be ready([code](https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L320)), it is the final status of ExternalSecret. That's why I skip the `ready` status.

**Comment by shuheiktgw** [comment]
> As we know, ClusterExternalSecret could create multiple ExternalSecrets, so I think it's reasonale to have an UX of ClusterExternalSecret to check the final status of all its related ExternalSecrets. At least it's friendly to our users.

Hmm, yes I agree that there is a case that shows the number of READTY statuses is helpful, but that is not the responsibility of the ClusterExternalSecret controller, so I still have to disagree with storing it to ClusterExternalSecret status.

> A synced ExternalSecret must be ready([code](https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L320)), it is the final status of ExternalSecret. That's why I skip the ready status.

For example, when I see `2/3` in the "SYNCED" column, that looks like 3 out of 2 ExternalSecrets are synced, but what it actually means is that 3 out of 2 ExternalSecrets are ready.

**Pull request closed without merging**
