### PR TITLE
Conjur E2E Tests for API Key Authentication

### PR DESCRIPTION
**Pull request by szh**
## Problem Statement

The CyberArk Conjur provider for ESO does not have E2E tests to verify that it works with Conjur OSS.

## Related Issue

Fixes #...

## Proposed Changes

This PR adds basic E2E tests for the GetSecret functionality, specifically with Conjur's API Key authentication (K8s JWT will be a separate PR). To do this, we added an "addon" which handles installing Conjur OSS via Helm and configuring it for the test suite.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by shuheiktgw** [comment]
Hi, @szh 👋 Thanks for the PR! Just a quick heads up, but we will likely merge https://github.com/external-secrets/external-secrets/pull/3017 soon, and this PR may need some modifications after that. I'll review this PR after merging the PR 🙇

**Comment by szh** [comment]
@shuheiktgw I did a rebase with no issues :)

**Comment by szh** [comment]
FYI I'm ready to add the PR for the JWT tests, but in the interest of keeping things simple I'll wait until the current PR is reviewed.

**Review by shuheiktgw — APPROVED** [review]
Sorry that I couldn't get back to this PR for a while 🙇 
LGTM

**Comment by shuheiktgw** [comment]
Wait until all the CI jobs pass

**Comment by szh** [comment]
Thank you @shuheiktgw! Do you want me to rebase?

**Comment by shuheiktgw** [comment]
@szh Yes, it seems the PR conflicts with the upstream. Would you resolve it? 🙂

**Comment by szh** [comment]
@shuheiktgw Rebased! As soon as this is merged, I'll put up my PR for the JWT tests.

**Comment by shuheiktgw** [comment]
@szh Thank you! Merging...

**Review by shuheiktgw — APPROVED** [review]

**Comment by szh** [comment]
Thank you so much @shuheiktgw! I've submitted the follow up PR for JWT - #3185

**Pull request merged**
