### PR TITLE
feat: add security best practices doc, restructure guides section

### PR DESCRIPTION
**Pull request by moolen**
Also towards: #2242 

CC @sebagomez i restructured the `guides` section as per comment.

Proof of work:
I though i would make a big :warning:  DANGER :warning: sign so people are aware of the data exfiltration risk. Not sure if it's too much, but if people care about security this is (IMO) the most important thing to care about.

eso-docs-security-best-practices-proof

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
also LGTM :)

**Comment by knelasevero** [comment]
LGTM

**Comment by knelasevero** [comment]
I have a "bigger" version of this, but a bit more opinionated, and also using other tools for admission control and other stuff. So it will come out as a blob maybe sometime.

**Pull request merged**
