### PR TITLE
fix: build a second image to fix the flux managed and unmanaged test

### PR DESCRIPTION
**Pull request by Skarlso**
## Problem Statement

The helm charts are built with the proxy name but the e2e test is running using the ghcr name to avoid various problems.

The flux test is pulling by the proxy name though which isn't a thing in the local kind cluster's registry or the registry for the managed test. Therefore, we build test versions for BOTH domains to make sure all tests are passing as they need to and chart fetching works as expected.

## Related Issue

Fixes #...

## Proposed Changes

How do you like to solve the issue and why?

## Checklist

- [ ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ ] All commits are signed with `git commit --signoff`
- [ ] My changes have reasonable test coverage
- [ ] All tests pass with `make test`
- [ ] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by Skarlso** [comment]
No idea what the linter is smoking
```
(base) ➜  external-secrets git:(test-fork-e2e) ✗ ct lint --config=.github/ci/ct.yaml
Linting charts...

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 external-secrets => (version: "0.10.3", path: "deploy/charts/external-secrets")
------------------------------------------------------------------------------------------------------------------------

Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "weave-gitops-enterprise-charts" chart repository (https://charts.dev.wkp.weave.works/charts-v3):
        Get "https://charts.dev.wkp.weave.works/charts-v3/index.yaml": dial tcp: lookup charts.dev.wkp.weave.works: no such host
...Unable to get an update from the "tf-controller" chart repository (https://weaveworks.github.io/tf-controller/):
        failed to fetch https://weaveworks.github.io/tf-controller/index.yaml : 404 Not Found
...Successfully got an update from the "1password" chart repository
...Successfully got an update from the "autoscaler" chart repository
...Successfully got an update from the "nginx-stable" chart repository
...Successfully got an update from the "karpenter" chart repository
...Successfully got an update from the "cert-manager" chart repository
...Successfully got an update from the "external-secrets" chart repository
...Successfully got an update from the "gitea-charts" chart repository
...Successfully got an update from the "datawire" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading bitwarden-sdk-server from repo oci://ghcr.io/external-secrets/charts
Deleting outdated charts
Pulled: ghcr.io/external-secrets/charts/bitwarden-sdk-server:v0.3.1
Digest: sha256:d41e67f43140aba5a30e01e34ec9a1007772ba411992d0ad9d165fbb35edc1e0
Linting chart "external-secrets => (version: \"0.10.3\", path: \"deploy/charts/external-secrets\")"
Validating /Users/skarlso/goprojects/kubernetes/external-secrets/deploy/charts/external-secrets/Chart.yaml...
Validation success! 👍
Validating maintainers...

Linting chart with values file "deploy/charts/external-secrets/ci/main-values.yaml"...

==> Linting deploy/charts/external-secrets

1 chart(s) linted, 0 chart(s) failed

------------------------------------------------------------------------------------------------------------------------
 ✔︎ external-secrets => (version: "0.10.3", path: "deploy/charts/external-secrets")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully

```

**Review by gusfcarvalho — APPROVED** [review]

**Pull request merged**
