### PR TITLE
Update webhook.port to other value than kubelet

### LINKED ISSUE #1981: port conflict for webhook on Fargate
**What happened**:

Using the default helm chart to run external dns on AWS Fargate there is a port conflict `10250` this port number is the default port for `kubelet`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Deploy EKS with Fargate, deploy helm chart to run pods on Fargate pods

The helm chart values.yaml default value `webhook.port` should be changed to another value like `9443`

### PR DESCRIPTION
**Pull request by csantanapr**
Fixes #1981

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
Hi @csantanapr ! Thanks for your PR and your interest in the project 🥳. We originally added the `10250` as a default because for many many clusters (GKE/EKS/AKS), there are some firewall rules/security group rules that are configured that prevent traffic on a sane default port like `9443`. We eventually switched to `10250` to be more compatible through most of the environments.

Some contexts here https://github.com/external-secrets/external-secrets/issues/956 and here https://github.com/external-secrets/external-secrets/issues/1378.

Having said that, I'd be fine to change those defaults. @moolen any thoughts?

**Comment by moolen** [comment]
I'm a little hesitant changing the default here as it will likely break users. Port 10250 is by default allowed in the security groups provided by  GKE/EKS terraform modules. It depends on a couple of factors whether or not the webhook port is actually accessible from the control plane, e.g. which CNI is used.

The best we can do here IMHO is to document when the defaults setting works and when to move away from it.

**Comment by csantanapr** [comment]
@gusfcarvalho @moolen 

I'm OK if the default port number is not changed, and instead docs are added to the chart like cert manager mentions the fact that the port `10250` could potential conflict with kubelet in `hostNetwork: true` which in case of Fargate the containers and kubelet share the same IP.

**Comment by gusfcarvalho** [comment]
As decided in today's community meeting - we are updating the docs to reflect the default Fargate case, and will close this PR. Thanks again for the interest and contribution @csantanapr !

**Comment by akvadrako** [comment]
I cannot find a mention of the fargate port in the docs. Was it ever added?

**Pull request closed without merging**
