### PR TITLE
sign images using cosign

### PR DESCRIPTION
**Pull request by cpanato**
- sign images using cosign
It signs the image when it builds the main branch and when doing a release

Fixes: #731 

cc @moolen

### CODE REVIEW

**Review by moolen — APPROVED** [review]
Thanks a lot! TIL how `keyless` signing works with cosign :blush:

**Review by cpanato — COMMENTED** [review]
@knelasevero @moolen realize that I forgot two things :( one to install coding in the pipeline and the other to enable an environment variable so sorry for the mistake and for breakinfmg the main branch, will submit a fix

**Comment by knelasevero** [comment]
We missed it as well :)

Coming from a fork ci changes have to get in for us to see them failing, happens from time to time!

**Comment by cpanato** [comment]
so sorry :(

**Pull request merged**
