### PR TITLE
Update the CyberArk Provider docs

### PR DESCRIPTION
**Pull request by benskelker**
## Problem Statement

Improve the CyberArk doc

## Related Issue

NA

## Proposed Changes

Update this doc page: https://external-secrets.io/latest/provider/conjur/

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
~- [ ] My changes have reasonable test coverage~ - NA
~- [ ] All tests pass with `make test`~- NA
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by shuheiktgw** [comment]
Hi @benskelker, thanks for your PR!
Your commits do not seem right and contain unrelated ones from Dependabot.  Could you fix them?

**Comment by benskelker** [comment]
> Hi @benskelker, thanks for your PR! Your commits do not seem right and contain unrelated ones from Dependabot. Could you fix them?

Thanks @shuheiktgw - should be ok now

**Review by shuheiktgw — APPROVED** [review]
Thank you for fixing them, @benskelker, and thank you for reviewing the PR, @szh!
Merging

**Comment by benskelker** [comment]
than you @shuheiktgw

**Pull request merged**
