### PR TITLE
Add FOSDEM23 talk

### PR DESCRIPTION
**Pull request by sagikazarmark**
## Problem Statement

Added my talk about External Secrets at FOSDEM '23

## Related Issue

None

## Proposed Changes

How do you like to solve the issue and why?

## Checklist

- [ ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ ] All commits are signed with `git commit --signoff`
- [ ] My changes have reasonable test coverage
- [ ] All tests pass with `make test`
- [ ] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
Awesome talk! Thanks for sharing the project!

**Comment by gusfcarvalho** [comment]
Awesome talk! Thanks for sharing the project!

**Comment by sagikazarmark** [comment]
@gusfcarvalho Thank you!

I have a longer version of the talk accepted in Open Source Summit NA. I'll post it here as well after the event.

**Comment by moolen** [comment]
Good Stuff, thanks for sharing this :heart:

**Pull request merged**
