### PR TITLE
[adopters] Adding `Pets at Home`

### PR DESCRIPTION
**Pull request by userbradley**
## Problem Statement

What is the problem you're trying to solve?
Adding pets at home as an adopter
## Related Issue

Fixes #...

## Proposed Changes

How do you like to solve the issue and why?

Adding Pets at Home

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage (md changes)
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable` (md changes)

### CODE REVIEW

**Comment by userbradley** [comment]
make reviewable

**Comment by knelasevero** [comment]
hi @userbradley, you need to clone the repo locally and run `make reviewable` in your terminal. Also you need to sign your commit. You can check how to do that here: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits.

**Comment by userbradley** [comment]
Hey @knelasevero I thought I had 

image

image

I think it may be causing issues with my email address.

**Comment by userbradley** [comment]
Apologies @knelasevero I have not done that signing before, so everything broke. That's now sorted and commits _should_ be verified now.

**Comment by knelasevero** [comment]
Seems like your GitHub main email is misconfigured

> Commit sha: 810b804, Author: Bradley, Committer: Bradley; Expected "Bradley 41597815+userbradley@users.noreply.github.com", but got "Bradley bstannard@petsathome.com".
Commit sha: c1390da, Author: Bradley, Committer: Bradley; The sign-off is missing.
Commit sha: 2933a70, Author: Bradley, Committer: Bradley; The sign-off is missing

**Comment by userbradley** [comment]
What's easiest for you? Open a new PR or should I try figure out how to edit previous commits?

**Comment by knelasevero** [comment]
you can "git rebase -i HEAD~3"
to interactively go over the last 3 commits
this will open the main editor with a text file listing the 3 commits
change "pick" for "edit" in each commit you wanna edit.

add the `Signed-off-by: name <correct@email>` to each commit

and save each time

at the end you have to force push

this is just for you to know :)

But I think it is easier if you create a new PR with correct stuff. Also, the complaint at that last commit `Commit sha: https://github.com/external-secrets/external-secrets/commit/810b80460670e4bd9998a16d4b09aa68f1da8d31, Author: Bradley, Committer: Bradley; Expected "Bradley [41597815+userbradley@users.noreply.github.com](mailto:41597815+userbradley@users.noreply.github.com)", but got "Bradley [bstannard@petsathome.com](mailto:bstannard@petsathome.com)".` is not about your local setup anymore, it is about your github email configured in your account. It is expecting `41597815+userbradley@users.noreply.github.com` which I think you don't wanna use. You have to change that in your github settings.

**Comment by userbradley** [comment]
Closing PR to open new one

**Pull request closed without merging**
