### PR TITLE
fix: use correct casing in docs for GitLab provider

### PR DESCRIPTION
**Pull request by maikelvl**
## Problem Statement

The official casing for GitLab is with a capital G and capital L.

## Proposed Changes

Case correction: Gitlab -> GitLab

This is not applicable in pascal/camel casing because GitLab is one word: e.g. 'GitlabProvider' or 'gitlabProvider'

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by moolen** [comment]
LGTM, thanks for this! Could you please sign your commit?

**Comment by maikelvl** [comment]
@moolen Thanks

I though I did that, but didn't push. It's fixed now. 😄

**Review by moolen — APPROVED** [review]
LGTM, thank you :heart:

*edit

Wait, the helm check failed, let me take a look shortly

**Comment by maikelvl** [comment]
I rebased the branch against main and pushed which triggered another pipeline

**Pull request merged**
