### PR TITLE
Add senhasegura DevOps Secrets Management (DSM) provider

### PR DESCRIPTION
**Pull request by lfraga**
Add [senhasegura DevOps Secrets Management (DSM)](https://senhasegura.com/) provider

This PR is a manual rebase of https://github.com/external-secrets/external-secrets/pull/830

### CODE REVIEW

**Comment by lfraga** [comment]
@knelasevero see https://github.com/external-secrets/external-secrets/pull/830#issuecomment-1115106933 please

**Comment by knelasevero** [comment]
Thanks @lfraga, great work!

**Comment by knelasevero** [comment]
Oh, my bad. @lfraga I just noticed that SS DSM is missing from https://external-secrets.io/main/stability-support/

Can you please add?

**Pull request merged**
