### PR TITLE
Optional path for Vault SecretStore

### PR DESCRIPTION
**Pull request by lhw**
* Backwards compatible change
  * Added tests to check for a range of possible combinations for paths

(Closes: #513)

### CODE REVIEW

**Comment by lhw** [comment]
Looks like some generated files need to be checked in due to the change to the CRD with the optional path. Do you have any process for that?

**Comment by knelasevero** [comment]
`make generate` would generate the crds.

I think you will also have to rebase with main

**Comment by knelasevero** [comment]
Hey @lhw, this lgtm, can you rebase and check the `check-diff` ci complain? :)

**Pull request merged**
