### PR TITLE
OCI Vault: Get secret by name from a specific Vault

### PR DESCRIPTION
**Pull request by EladGabay**
Following to https://github.com/external-secrets/external-secrets/issues/587
add Vault ID field to the SecretStore, then use the ExternalSecret's key as a secret name in the provided Vault.

### CODE REVIEW

**Comment by EladGabay** [comment]
@knelasevero FYI :)

**Comment by knelasevero** [comment]
Hey @EladGabay , thanks for the PR!

Can you also update the docs for this provider?

**Comment by EladGabay** [comment]
> Hey @EladGabay , thanks for the PR!
> 
> Can you also update the docs for this provider?

Sure, updated.

I'm trying to check it using regular helm install with the specific commit in tag instead of `main` (https://external-secrets.io/guides-using-latest-image). I use `v0.3.11-49.dbedbedb`, seems like no image. Could you please provide the tag I should check with, and I'll validate it works like expected?

Thanks!

**Comment by EladGabay** [comment]
@knelasevero Anything else should I update?

**Comment by EladGabay** [comment]
> > Hey @EladGabay , thanks for the PR!
> > Can you also update the docs for this provider?
> 
> Sure, updated.
> 
> I'm trying to check it using regular helm install with the specific commit in tag instead of `main` (https://external-secrets.io/guides-using-latest-image). I use `v0.3.11-49.dbedbedb`, seems like no image. Could you please provide the tag I should check with, and I'll validate it works like expected?
> 
> Thanks!

Verified locally (with my own registry).

**Comment by knelasevero** [comment]
Hey, sorry, 

last time I had to push the image. Glad you were able to test it with your own registry.

I will let e2e tests run just cause we have crd changes (I know it shouldn't affect, but doesn't hurt).

Will merge after that.

**Comment by knelasevero** [comment]
@EladGabay would you be willing to help us maintain this provider, since you are able to test it with the real workflow?

If you would be happy to do it, please add your username in the readme.

No worries if you don't want to, btw :)

**Comment by EladGabay** [comment]
> @EladGabay would you be willing to help us maintain this provider, since you are able to test it with the real workflow?
> 
> If you would be happy to do it, please add your username in the readme (in the community maintained section).
> 
> No worries if you don't want to, btw :)

I'll add

**Pull request merged**
