### PR TITLE
Add ESO Twitter Account

### PR DESCRIPTION
**Pull request by eminalemdar**
I've added ESO Twitter Account to How to get involved part of the documentation.

### CODE REVIEW

**Comment by knelasevero** [comment]
Who is managing this account that I was not aware about? :sweat_smile:

**Comment by gusfcarvalho** [comment]
We at CS created it during this week. I’ll add login information to the 1Password once we get it.

**Comment by knelasevero** [comment]
Oh, ok ;)

**Comment by gusfcarvalho** [comment]
Paul doesn't like me anymore :(

**Pull request merged**
