### PR TITLE
Add support for specifying extra manifests via helm

### PR DESCRIPTION
**Pull request by upodroid**
## Problem Statement

Fixes: https://github.com/external-secrets/external-secrets/issues/2961
Closes: #3417

## Proposed Changes

How do you like to solve the issue and why? Explained in the issue.

## Checklist

- [X] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [X] All commits are signed with `git commit --signoff`
- [X] My changes have reasonable test coverage
- [X] All tests pass with `make test`
- [X] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
hi @upodroid ! I believe this is a duplicate from https://github.com/external-secrets/external-secrets/pull/3417. While I don't mind that - same comments there apply here. Can you please add a simple helm unittest to make sure we have coverage for this feature? 😄 It could be a service account addition for what it's worth.

**Comment by upodroid** [comment]
I didn't see that PR, he forgot to xref the issue. I'll fix the unit test now.

**Comment by upodroid** [comment]
This PR was helpful.

https://github.com/traefik/traefik-helm-chart/pull/643

**Review by gusfcarvalho — APPROVED** [review]

**Comment by gusfcarvalho** [comment]
@upodroid  thank you for your contribution (on a sunday!) 😄

**Pull request merged**
