### PR TITLE
Add ability provide CA for Yandex' Lockbox provider

### PR DESCRIPTION
**Pull request by vovcyan**
Currently Yandex Lockbox provider has an ability to provide the custom endpoint which can be production/testing/etc. Sometimes,  the certificates of these endpoints issued by the local provider.
In this case needs to add an ability to provide custom Certificate authority (CA) too.

### CODE REVIEW

**Comment by vovcyan** [comment]
@AndreyZamyslov

As code owner of Lockbox provider, cloud you take a loop at my changes, please?

**Comment by AndreyZamyslov** [comment]
LGTM in general

**Comment by vovcyan** [comment]
@knelasevero

Hi Lucas, cloud you please take a look at my changes?

**Comment by knelasevero** [comment]
Hey @vovcyan I'm on sick leave. Will have a look as soon as I am back.

@gusfcarvalho @moolen can also have a look if they have some time

**Comment by moolen** [comment]
hey @vovcyan the implementation looks good to me so far. Can you please add tests to verify that `caCertificate` is looked up on a secret and passed to the lockbox client, would that be possible?

**Comment by vovcyan** [comment]
> hey @vovcyan the implementation looks good to me so far. Can you please add tests to verify that `caCertificate` is looked up on a secret and passed to the lockbox client, would that be possible?

Hey @moolen
Ok, I'll try my best ;)

**Comment by vovcyan** [comment]
Hey @moolen @knelasevero 

I've added tests to verify that `caCertificate` is available in secrets.
Could you please take a look at my changes?

**Comment by moolen** [comment]
LGTM! Awesome, thank you for the contribution :heart:!

**Pull request merged**
