### PR TITLE
Revert "GetAllSecrets CRD and Azure implementation"

### PR DESCRIPTION
**Pull request by knelasevero**
Reverts external-secrets/external-secrets#613 (created just using github revert button)

### CODE REVIEW

**Comment by knelasevero** [comment]
@moolen I am thinking about just merging this one, clicking again the revert button of this one, and leaving the next PR open so Seb can fix the v1alpha1 version as well there

**Review by sebagomez — APPROVED** [review]
LGTM

**Review by moolen — APPROVED** [review]
sure, we can do that!

**Pull request merged**
