### PR TITLE
Password yaml was missing the name

### PR DESCRIPTION
**Pull request by sebagomez**
## Problem Statement

The yaml provided as example for Password was broken.
I also thought it could be usefull to provide an External Secret that uses the Password from the example

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [ ] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Review by moolen — APPROVED** [review]
LGTM, well done :bow:  :+1: 
Funny coincidence, we've talked about this very issue last week that generators don't have `ExternalSecret`s in their examples.

**Comment by sebagomez** [comment]
Yes, I realized it could be useful... will add some more

**Comment by sebagomez** [comment]
Should I create an issue for it?

**Comment by moolen** [comment]
Yeah sure, sounds good, thanks!

**Pull request merged**
