### PR TITLE
Demonstrate new slices/maps packages

### PR DESCRIPTION
**Pull request by BooleanCat**
## Problem Statement

Demonstrate how it's possible to simplify some code with Go 1.23

## Related Issue

None.

## Proposed Changes

Make use of the new slices and maps packages.

## Checklist

- [X] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [X] My changes have reasonable test coverage
- [X] All tests pass with `make test`
- [X] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by Skarlso** [comment]
Niceee :)

**Comment by BooleanCat** [comment]
@Skarlso  I wanted to familiarise you folks with the new `iter.Seq` functionality in Go 1.23 to:

1. Show how some code could be simplified
2. Selfishly demonstrate a package I maintain that you may or may not find useful.

For (2) I wanted to introduce [go-functional](https://github.com/BooleanCat/go-functional) - an iterator library for Go.

Using if you could do things like this:

This:

```go
for _, resource := range resources {
	if !nameRegexp.MatchString(resource.Name) {
		continue
	}
	secret, err := provider.getPassboltSecret(ctx, resource.ID)
	if err != nil {
			return nil, err
	}
	marshaled, err := utils.JSONMarshal(secret)
	if err != nil {
		return nil, err
	}
	res[resource.ID] = marshaled
}
```

Becomes this:

```go
isResource := func(r api.Resource) bool { return nameRegexp.MatchString(r.Name) }

for resource := range itx.FromSlice(resources).Filter(isResource) {
	secret, err := provider.getPassboltSecret(ctx, resource.ID)
	if err != nil {
		return nil, err
	}
	marshaled, err := utils.JSONMarshal(secret)
	if err != nil {
		return nil, err
	}
	res[resource.ID] = marshaled
}
```

**Comment by Skarlso** [comment]
@BooleanCat also, please don't take this the wrong way, but if we DID use any kind of third party library for stuff like that, we would likely choose something that is super widely used and popular like https://github.com/samber/lo.

But more likely is that we keep things close to hearth since this is a security utility.

**Comment by Skarlso** [comment]
> Keeping things simple makes sense! samber/lo is great but was written prior to iterators being supported by the language so it's not as ergonomic to efficiently loop over the collections as it would be with go-functional.

Well... https://github.com/samber/lo/pull/439 :) They are considering creating a subpackage called `iter`. :)

**Review by Skarlso — APPROVED** [review]

**Pull request merged**
