### PR TITLE
Small typo fix guides-multi-tenancy.md

### PR DESCRIPTION
**Pull request by sixlettervariables**
Fixes a minor typo in the docs.

### CODE REVIEW

**Comment by moolen** [comment]
hey @sixlettervariables could you please sign your commit? 🙏

**Comment by sixlettervariables** [comment]
I did it via GitHub on my phone, so it's a little strange to see it isn't signed/verified (they usually are).

**Comment by sixlettervariables** [comment]
Appears it is signed/verified:
Screenshot_20220829-133120

**Comment by moolen** [comment]
true, it's verified by GitHub but it's not having a `Signed-off-by: <Name> <email>` commit message footer. This is required to make our DCO bot happy 😅

**Comment by sixlettervariables** [comment]
Okay, I'll see if GitHub mobile allows me to amend that commit.

**Comment by sixlettervariables** [comment]
@moolen wasn't possible via mobile and had to wait til I got to the house.

**Comment by moolen** [comment]
I enabled that feature, thanks for pointing that out, i wasn't aware of that :+1:

**Review by moolen — APPROVED** [review]

**Pull request merged**
