### PR TITLE
Add MBTI as adopter

### PR DESCRIPTION
**Pull request by Benny-Git**
Added Mercedes-Benz Tech Innovation to the list of adopters, as we use the project in at least one of our projects.

Benjamin Bertow benjamin.bertow@mercedes-benz.com, Mercedes-Benz Tech Innovation GmbH. https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
hello @Benny-Git !! Thanks a lot for adding MBTI as an adopter!

**Comment by gusfcarvalho** [comment]
@Benny-Git - do you have a slack channel/user that I can reach out to you? :)

**Comment by Benny-Git** [comment]
@gusfcarvalho Easiest would be via mail, I think.

**Pull request merged**
