### PR TITLE
docs: add project roadmap to docs

### PR DESCRIPTION
**Pull request by moolen**
This PR adds docs around our project roadmap. The roadmap is used to show our plans towards GA to an enduser. The actual issues/TODOs are tracked in the linked Github project board.

@sebagomez: We want to maintain the `kubernetes` provider to internally.
@ahmedmus-1A @asnowfix @1A-mj: We want to maintain the `azure` provider internally.

Declaring both providers as being project maintained should help with community adoption. Please let me know if you have any questions or suggestions.

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
@rodrmartinez i think you are involved with kubernetes provider as well :)

**Comment by asnowfix** [comment]
Sorry I missed your call-out @moolen . No issue wrt/ internal azure provider maintenance AFAIAC.  Note that @ahmedmus-1A & @1A-mj are no more part of the project, Amadeus-wise.  We have 2 new Amadeus contributors: @dreadful-dragon (that you have already accepted a PR from) & @paulpozicheun.

**Comment by moolen** [comment]
Thanks for the update, great to see new contributors coming from Amadeus :heart:

**Pull request merged**
