### PR TITLE
Azure keyvault non default cloud

### LINKED ISSUE #428: azure key vault provider is not working with azure china
### Discussed in https://github.com/external-secrets/external-secrets/discussions/418

<div type='discussions-op-text'>

<sup>Originally posted by **sreejithsoman-mc** October  7, 2021</sup>
Hi ,

I was trying the setup external secret for azure provider. I am using **azure china.**

In SecretStore , I have provided the vaultUrl to my vault in azure china.

But when i configure my external-secret resource i get below error

` Message:               could not get secret data from provider: key "secret/monitoring-basic-auth" from ExternalSecret "monitoring-basic-auth": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://kv-******-****.vault.azure.cn/secrets/monitoring-basic-auth/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'e6106e37-****-*****-****-b4d47d166082' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.\r\nTrace ID: 3e1ca0dd-5bbf-4bc8-bcaa-5ca829424f00\r\nCorrelation ID: 4072128e-a063-4e84-bf26-edea7baf26d8\r\nTimestamp: 2021-10-07 05:50:24Z","error_codes":[90002],"timestamp":"2021-10-07 05:50:24Z","trace_id":"3e1ca0dd-5bbf-4bc8-bcaa-5ca829424f00","correlation_id":"4072128e-a063-4e84-bf26-edea7baf26d8","error_uri":"https://login.microsoftonline.com/error?code=90002"} Endpoint https://login.microsoftonline.com/e6106e37-******-*******-*****-b4d47d166082/oauth2/token?api-version=1.0`

Looks like it is trying to connect to azure global.  Will this support azure china?</div>

### PR DESCRIPTION
**Pull request by stefan-schweer**
Allows to set active directory endpoint and active directory resource in the secretstore

Closes #428

### CODE REVIEW

**Comment by stefan-schweer** [comment]
I tested it manually in china, i don't have a public cloud cluster for testing right now, but i might be able to do that within the next week.

**Comment by knelasevero** [comment]
https://github.com/external-secrets/external-secrets/runs/4099099789?check_suite_focus=true

**Comment by knelasevero** [comment]
Hi, if you rebase with main, you can now run e2e tests for specific cloud providers. 

First export some of the required credentials:

```
export TENANT_ID=asd98934-6c5.........
export VAULT_URL="https://YOURVAULT.vault.azure.net/"
export AZURE_CLIENT_ID="asd29342893.............."
export AZURE_CLIENT_SECRET="keysecretvalue"
```

then you can run them locally with: 

```
BUILD_ARGS="--build-arg TARGETARCH=amd64 --build-arg TARGETOS=linux" make test.e2e FOCUS="azure"
```

**Comment by vazul** [comment]
Hi @stefan-schweer , regarding the failing check-diff, it is related to go version 1.17. Use go 1.16, or simple remove the first line of the generated deepcopy files.

**Comment by stefan-schweer** [comment]
I really struggle to find time for testing that it non china, what irritates me is that the only tests (make test) that are failing for me in my branch are failing on main too.

**Comment by knelasevero** [comment]
Unit tests failing on main usually are controller tests trying to use kubebuilder's envtest, and not being able to:

```
export KUBEBUILDER_TOOLS_VERSION='1.20.2' # check for latest version or a version that has support to what you are testing

curl -sSLo envtest-bins.tar.gz "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-$KUBEBUILDER_TOOLS_VERSION-linux-amd64.tar.gz"

sudo mkdir -p /usr/local/kubebuilder
sudo tar -C /usr/local/kubebuilder --strip-components=1 -zvxf envtest-bins.tar.gz
```

But last time the problem was e2e tests, not unit tests

Let me send another /ok-to-test, one sec

**Comment by knelasevero** [comment]
To run e2e tests you run `make test.e2e` instead of `make test`

More preciselly: `BUILD_ARGS="--build-arg TARGETARCH=amd64 --build-arg TARGETOS=linux" make test.e2e FOCUS="azure"`

Please have a look over above comment https://github.com/external-secrets/external-secrets/pull/430#issuecomment-975735470

**Comment by knelasevero** [comment]
@stefan-schweer do you plan to get back to this?

**Comment by knelasevero** [comment]
Hey @stefan-schweer  we are closing this PR since we got no response, but feel free to comment here and we can reopen if you have time to get back to this :)

**Pull request closed without merging**
