### PR TITLE
Included metadataPolicy: Fetch in K8s provider

### LINKED ISSUE #1873: Add MetadataPolicy=Fetch for Kubernetes
`MetadataPolicy: Fetch` is already implemented for Azure KeyVault. We need to implement it for Kubernetes provider in order to allow information to be obtained from `secret.metadata.annotations` and `secret.metadata.labels`. Labels and Annotations should be obtained from the `remoteRef`, by selecting a property like:

```
data:
- metadataPolicy: Fetch
   secretKey: my-key
   remoteRef:
     key: labels
     property: "labels.my-own-label"
- metadataPolicy: Fetch
   secretKey: my-key
   remoteRef:
     key: path-to-my-secret
     property: "annotations.my-own-annotation"
```

### PR DESCRIPTION
**Pull request by sebagomez**
Fixes #1873 

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x] All commits are signed with `git commit --signoff`
- [x] My changes have reasonable test coverage
- [x] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by sebagomez** [comment]
Guys, I have a question regarding [this function](https://github.com/external-secrets/external-secrets/pull/2091/files#diff-8e6c015cd7592cc7f8958f9bf6a0097c4beed7819f421ec5d275c89000a95f9bR71).
If I don't use it and use a regular `json.Marshal` os a map[string][]byte I get a json with labels and annotations and their values would be base64 encoded.
If on the other hand I transfer that to a map[string]string, if I json.Marshal it I get the values as an encaped json string.
Only when I use the function, not a fan of string concatenation, I get a proper json that's then "searchable". BUT, using this function, if I don't set a property in the ExternalSecret I get a json like the following.

```json
{
  "annotations": "{\"date\":\"today\",\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"v1\\\",\\\"data\\\":{\\\"token\\\":\\\"cm9vdA==\\\"},\\\"kind\\\":\\\"Secret\\\",\\\"metadata\\\":{\\\"annotations\\\":{\\\"date\\\":\\\"today\\\",\\\"my\\\":\\\"annotations\\\"},\\\"labels\\\":{\\\"dev\\\":\\\"seb\\\",\\\"provider\\\":\\\"kubernetes\\\"},\\\"name\\\":\\\"source-secret\\\",\\\"namespace\\\":\\\"remote\\\"}}\\n\",\"my\":\"annotations\"}",
  "labels": "{\"dev\":\"seb\",\"provider\":\"kubernetes\"}"
}
```
which again, it's a json object with two properties (labels and annotations) and strings as values, which it's not what I want. 
What would be the right way of getting the proper json? I'm sure some of you have probably encounter this issue before.

**Comment by gusfcarvalho** [comment]
> Guys, I have a question regarding [this function](https://github.com/external-secrets/external-secrets/pull/2091/files#diff-8e6c015cd7592cc7f8958f9bf6a0097c4beed7819f421ec5d275c89000a95f9bR71). If I don't use it and use a regular `json.Marshal` os a map[string][]byte I get a json with labels and annotations and their values would be base64 encoded. If on the other hand I transfer that to a map[string]string, if I json.Marshal it I get the values as an encaped json string. Only when I use the function, not a fan of string concatenation, I get a proper json that's then "searchable". BUT, using this function, if I don't set a property in the ExternalSecret I get a json like the following.
> 
> ```json
> {
>   "annotations": "{\"date\":\"today\",\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"v1\\\",\\\"data\\\":{\\\"token\\\":\\\"cm9vdA==\\\"},\\\"kind\\\":\\\"Secret\\\",\\\"metadata\\\":{\\\"annotations\\\":{\\\"date\\\":\\\"today\\\",\\\"my\\\":\\\"annotations\\\"},\\\"labels\\\":{\\\"dev\\\":\\\"seb\\\",\\\"provider\\\":\\\"kubernetes\\\"},\\\"name\\\":\\\"source-secret\\\",\\\"namespace\\\":\\\"remote\\\"}}\\n\",\"my\":\"annotations\"}",
>   "labels": "{\"dev\":\"seb\",\"provider\":\"kubernetes\"}"
> }
> ```
> 
> which again, it's a json object with two properties (labels and annotations) and strings as values, which it's not what I want. What would be the right way of getting the proper json? I'm sure some of you have probably encountered this issue before.
> 
> Edit: Even with the current state (doing string concatenation) if I set the `labels` property I get a proper json
> 
> ```json
> {
>   "dev": "seb",
>   "provider": "kubernetes"
> }
> ```

I think what you could do here is to do a marshal to map[string]interface{} and then Marshal it. It should produce the correct outcome. After that, you can use `gjson` to operate over it (here is an example in hashivault codebase: https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/vault/vault.go#L644-L681)

**Comment by sebagomez** [comment]
Thanks @gusfcarvalho, I did try your suggestion before but it's base64 encoding the values. 
So this is what I'm getting right now

```json
{
  "annotations": "eyJkYXRlIjoidG9kYXkiLCJrdWJlY3RsLmt1YmVybmV0ZXMuaW8vbGFzdC1hcHBsaWVkLWNvbmZpZ3VyYXRpb24iOiJ7XCJhcGlWZXJzaW9uXCI6XCJ2MVwiLFwiZGF0YVwiOntcInRva2VuXCI6XCJjbTl2ZEE9PVwifSxcImtpbmRcIjpcIlNlY3JldFwiLFwibWV0YWRhdGFcIjp7XCJhbm5vdGF0aW9uc1wiOntcImRhdGVcIjpcInRvZGF5XCIsXCJteVwiOlwiYW5ub3RhdGlvbnNcIn0sXCJsYWJlbHNcIjp7XCJkZXZcIjpcInNlYlwiLFwicHJvdmlkZXJcIjpcImt1YmVybmV0ZXNcIn0sXCJuYW1lXCI6XCJzb3VyY2Utc2VjcmV0XCIsXCJuYW1lc3BhY2VcIjpcInJlbW90ZVwifX1cbiIsIm15IjoiYW5ub3RhdGlvbnMifQ==",
  "labels": "eyJkZXYiOiJzZWIiLCJwcm92aWRlciI6Imt1YmVybmV0ZXMifQ=="
}
```

Which makes it impossible to find th `label.dev` property and even if I ask for the `label` property, the generated secret would be twiced base64 encoded.

I'll keep looking for options, I've seen some people recommending implementing my own `MarshalJSON` method, which I think it's what I need to do. 

Let me know if you see any other/better alternative. Cheers

**Comment by gusfcarvalho** [comment]
maybe

> Thanks @gusfcarvalho, I did try your suggestion before but it's base64 encoding the values. So this is what I'm getting right now
> 
> ```json
> {
>   "annotations": "eyJkYXRlIjoidG9kYXkiLCJrdWJlY3RsLmt1YmVybmV0ZXMuaW8vbGFzdC1hcHBsaWVkLWNvbmZpZ3VyYXRpb24iOiJ7XCJhcGlWZXJzaW9uXCI6XCJ2MVwiLFwiZGF0YVwiOntcInRva2VuXCI6XCJjbTl2ZEE9PVwifSxcImtpbmRcIjpcIlNlY3JldFwiLFwibWV0YWRhdGFcIjp7XCJhbm5vdGF0aW9uc1wiOntcImRhdGVcIjpcInRvZGF5XCIsXCJteVwiOlwiYW5ub3RhdGlvbnNcIn0sXCJsYWJlbHNcIjp7XCJkZXZcIjpcInNlYlwiLFwicHJvdmlkZXJcIjpcImt1YmVybmV0ZXNcIn0sXCJuYW1lXCI6XCJzb3VyY2Utc2VjcmV0XCIsXCJuYW1lc3BhY2VcIjpcInJlbW90ZVwifX1cbiIsIm15IjoiYW5ub3RhdGlvbnMifQ==",
>   "labels": "eyJkZXYiOiJzZWIiLCJwcm92aWRlciI6Imt1YmVybmV0ZXMifQ=="
> }
> ```
> 
> Which makes it impossible to find th `label.dev` property and even if I ask for the `label` property, the generated secret would be twiced base64 encoded.
> 
> I'll keep looking for options, I've seen some people recommending implementing my own `MarshalJSON` method, which I think it's what I need to do.
> 
> Let me know if you see any other/better alternative. Cheers

Since we know it's only `labels` and `annotations` what we could do is just define as a big weird `map[string]map[string]string` (and only load labels and annotations to that map). This way I'm pretty sure the Marshal would work OOTB.

Or setup two `map[string]string`, one for labels and one for annotations.

**Comment by sebagomez** [comment]
ChatGPT FTW!

```golang
import "encoding/json"

m := map[string]json.RawMessage{
    "foo": json.RawMessage(`{"a": 1, "b": 2}`),
    "bar": json.RawMessage(`{"c": 3, "d": 4}`),
}

jsonBytes, err := json.Marshal(m)
if err != nil {
    panic(err)
}

jsonString := string(jsonBytes)

fmt.Println(jsonString)
```

`map[string]json.RawMessage` is the key!

**Comment by sebagomez** [comment]
Can anybody help me out here?
I don't understand what I need to do :( 

https://github.com/external-secrets/external-secrets/actions/runs/4365716404/jobs/7634734518

**Comment by knelasevero** [comment]
Can you create a new branch (from main) with a single commit with your new changes there and re-open the PR (with a Signed-off-by: ___)?

**Comment by sebagomez** [comment]
> Can you create a new branch (from main) with a single commit with your new changes there and re-open the PR (with a Signed-off-by: ___)?

Will definitely do that, thanks Lucas. I'm closing this one

**Pull request closed without merging**
