### PR TITLE
New Generator for UUIDs

### PR DESCRIPTION
**Pull request by aschaber1**
## Problem Statement

I'd like to generate uuids for use as input values in flux' `HelmReleases`.

## Related Issue

n/a

## Proposed Changes

I added a new generator that uses google's uuid library (https://pkg.go.dev/github.com/google/uuid).
I'm not a developer, please help me implement this feature and get it across the line.

## Checklist

- [x] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [X] All commits are signed with `git commit --signoff`
- [X] My changes have reasonable test coverage
- [X] All tests pass with `make test`
- [x] I ensured my PR is ready for review with `make reviewable`

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
Hi! Can you please run `make lint` and correct all the linting errors of your PR please? Thanks! 😄

**Comment by Skarlso** [comment]
> > Hi! Can you please run `make lint` and correct all the linting errors of your PR please? Thanks! 😄
> 
> 
> 
> @gusfcarvalho Thank you for your feedback :) I linted as much as I can, but I'm uncertain about the remaining messages as I'm not sure, wether I'm "allowed" to change the signature (as in parameters) of the functions. Could you please advise. 

Sure. Go for it. You can change whatever you want as long as it makes sense and is readable.

**Comment by Skarlso** [comment]
@aschaber1 Are you planning on continuing this? :)

**Comment by aschaber1** [comment]
> @aschaber1 Are you planning on continuing this? :)

took me a minute to get back to this. it's rebased and now all these pass:
- `make reviewable`
- `make lint`
- `make fmt`

hope this works :)

**Comment by Skarlso** [comment]
@aschaber1 please also add a descriptor with samples to the api guides under `docs/api/generators`. Thanks :) 🙇

**Comment by Skarlso** [comment]
And you need to also add that doc to mkdocs.yaml under hack/api-docs I think.
```
 - Generators:
      - "api/generator/index.md"
      - Azure Container Registry: api/generator/acr.md
      - AWS Elastic Container Registry: api/generator/ecr.md
      - Google Container Registry: api/generator/gcr.md
      - Vault Dynamic Secret: api/generator/vault.md
      - Password: api/generator/password.md
      - Fake: api/generator/fake.md
      - Webhook: api/generator/webhook.md
      - Github: api/generator/github.md
```

**Comment by Skarlso** [comment]
Thanks, I'll take a look. :)

**Comment by aschaber1** [comment]
Thank you @Skarlso for the guidance. I added the docs and rebased again `main`.

**Review by Skarlso — APPROVED** [review]

**Pull request merged**
