### PR TITLE
add concurrent flag to allow more reconciles at the same time

### PR DESCRIPTION
**Pull request by jack-evans**
addresses #330 - enables the operator to deal with more than 1 reconcile concurrently at a time

### CODE REVIEW

**Comment by knelasevero** [comment]
@jack-evans  Should we explicitly have new args for this in the helm templates? https://github.com/external-secrets/external-secrets/blob/54c1a3d9d81f2b5b5efa8e5f98431ffea808bf1b/deploy/charts/external-secrets/templates/deployment.yaml#L43

**Comment by jack-evans** [comment]
> @jack-evans  Should we explicitly have new args for this in the helm templates? https://github.com/external-secrets/external-secrets/blob/54c1a3d9d81f2b5b5efa8e5f98431ffea808bf1b/deploy/charts/external-secrets/templates/deployment.yaml#L43

We could do if we think it's more reasonable than defining within the extraArgs part? I'm happy to do that if we think so

**Comment by jack-evans** [comment]
> @jack-evans Should we explicitly have new args for this in the helm templates?
> 
> https://github.com/external-secrets/external-secrets/blob/54c1a3d9d81f2b5b5efa8e5f98431ffea808bf1b/deploy/charts/external-secrets/templates/deployment.yaml#L43

@knelasevero have made the changes, let me know what you think? :)

**Comment by knelasevero** [comment]
Sorry, did you test running this? I had some trouble making this work for some reason. I forgot to report back here with the error. Will do it soon

**Comment by knelasevero** [comment]
Also, can you rebase with main branch please?

**Comment by jack-evans** [comment]
Hey @knelasevero - I did do a quick test but will rebase, build locally and test again 🙂

**Comment by knelasevero** [comment]
@jack-evans do you plan to get back to this one?

**Comment by jack-evans** [comment]
@knelasevero sorry about that, was very busy with the day job! I ran locally and found a little issue with the helm chart so have fixed that up. tested a very basic example of 4 ES custom resources with a concurrent flag of 2 and saw that they got successfully applied. Feel free to have a test too 🙂

**Comment by knelasevero** [comment]
If it is not about the code that you sent, don't worry :)

Seems like check-diff is also failing. I think different versions are putting `//go:build !ignore_autogenerated` on top of generated files and we are not using them like that yet.

Let me send a /ok-to-test as well

**Comment by jack-evans** [comment]
Ahh gotcha, I can manually remove if needed!

**Comment by knelasevero** [comment]
Please remove those changes to the generated files, yes :)

**Comment by jack-evans** [comment]
@knelasevero are you around to review this?

**Comment by knelasevero** [comment]
LGTM from my side :)

@moolen can you have a look?

**Comment by knelasevero** [comment]
I know it would probably be better to discuss in a new issue, but do we want to have all important args explicit in the helm chart instead of passing most of them in extra args (not the scope of this PR, just asking since it was one of the things we did here)?

**Pull request merged**
