### PR TITLE
Yandex Lockbox Connection Leaks

### PR DESCRIPTION
**Pull request by AndreyZamyslov**
Fixes the issue: https://github.com/external-secrets/external-secrets/issues/833

### CODE REVIEW

**Comment by AndreyZamyslov** [comment]
@knelasevero @moolen Could you please take a look at the changes?

**Comment by moolen** [comment]
LGTM, thanks for the fix! FYI: we plan on doing the `0.5.0` release in the next ~2 weeks. Let us know if this must be released urgently.

**Comment by AndreyZamyslov** [comment]
> we plan on doing the `0.5.0` release in the next ~2 weeks. Let us know if this must be released urgently.

There's no urgency, so I think we'll just wait for a new version
Thank you!

**Pull request merged**
