### PR TITLE
chore: refactor es ctrl tests

### PR DESCRIPTION
**Pull request by moolen**
refactor controller tests to use ginkgo table-drive tests.

Also adds 1 testcase to test template update mechanics

### CODE REVIEW

**Comment by moolen** [comment]
i looked into the codecov change, i can't tell where that could come from :shrug:. I checked `main` too and there it's also not covered :thinking:

**Comment by knelasevero** [comment]
Codecov is too agressvie... It is marking 100% of our PRs as brocken... I looked over a bit and could not find a good way to set it to have a bit of a normal threshold. Would be good maybe to allow something like -2% cov? Sometimes we are not adding anything, just changing something in a line, and it also marks the PR as decreasing cov. Maybe we should look at what other similar projects are doing. Or just letting codecov report on stuff, but not mark PRs as brocken

**Pull request merged**
