### PR TITLE
fix: ensure that data is being deleted when using tpl

### LINKED ISSUE #315: Deleting one/more key-value pair from the secret in AWS SM does not remove from the K8s Secrets
**Describe the solution you'd like**
Deleting one/more key-value pair from the secret in AWS SM, the sync does not remove those removed key-value pairs. Using `dataFrom`.

**What is the added value?**
The secrets generated by external secrets must be representative of what is in the AWS SM.

**Give us examples of the outcome**

Assume this is the initial secret store in the AWS SM.

```json
{
  "REDIS_PASSWORD": "rPassword",
  "REDIS_USERNAME": "rUsername",
  "FOO": "BAR",
  "BAZ": "BAN"
}
```
No if I remove the secret `FOO` and `BAZ` from the above defined secret, post the sync interval both `FOO` and `BAZ` still remain in the k8s secrets generated by external secrets.

**Observations (Constraints, Context, etc):**
NA

### PR DESCRIPTION
**Pull request by moolen**
Fixes #315 

When using `spec.Target.Template` with an empty `spec.Target.Template.Data` the secret. That was caused by this particular code path:

https://github.com/external-secrets/external-secrets/blob/0b9c142a22b98c0845bc15dcfb5992d1ddc2aaa1/pkg/controllers/externalsecret/externalsecret_controller_template.go#L64-L71

This PR fixes it and adds test cases for it.

### CODE REVIEW

**Comment by moolen** [comment]
I dunno but codecov shouldn't _really_ care about `*_test.go` files. WDYT?

**Comment by knelasevero** [comment]
Added you as admin. https://sonarcloud.io/project/settings?category=exclusions&id=external-secrets_external-secrets

I have now added exclusions for **/e2e/** and **/*_test.go

Let's see if it works

**Comment by knelasevero** [comment]
Oh, and we can remove that codecov file. We wanted to add coveralls, bit did not happen yet. And duplication was reported by sonar :sweat_smile:

**Comment by knelasevero** [comment]
SInce sonar cloud is now working in pull strategy instead of push strategy, it will only run with a new commit I think (or forcepush)

**Pull request merged**
